### ISSUE TITLE
[Site]: remove es language 

### ISSUE THREAD

**Issue by SkyeYoung** [iresty/iresty.github.io#1003]
### Current State

**Description of the current state/issue**:
I think we don't need es(Spanish) for now. There was a contributor doing Spanish and he passed away about a year ago, then the process of translation is stopped, see https://github.com/apache/apisix/issues/3587#issuecomment-818397330.

I  would suggest to transfer this part as an issue and see if anyone could pick it up.

```suggestion
const languages = ['en', 'zh'];
```

_Originally posted by @yzeng25 in https://github.com/apache/apisix-website/pull/1002#discussion_r841056808_

**Link to the page**:
https://github.com/apache/apisix-website/blob/89cf0e1031fa4d7f2b2e37942e07122081a163c3/scripts/common.js#L44

**Screenshots (if relevant)**:
none

### Desired State

**Description of the change you are proposing**:

### Would you like to fix this issue?

No. Please assign another contributor

**Comment by juzhiyuan** [comment]
How to fix this?

1. Visit https://github.com/apache/apisix-website/blob/master/scripts/common.js#L44.
![image](https://user-images.githubusercontent.com/2106987/162405987-f297d96c-4a77-42ca-93f8-ccb81247a1f6.png)
2. Click `Edit this file` button.
3. Remove `'es'` from Line 44.
5. Submit PR.

**Comment by adarrssh** [comment]
Can I work on this issue?

**Comment by yzeng25** [comment]
@adarrssh sure :)

**Comment by yzeng25** [comment]
Any updates or expected due date here @adarrssh ?

**Comment by SkyeYoung** [comment]
> Any updates or expected due date here @adarrssh ?

@yzeng25 https://github.com/apache/apisix-website/pull/1013 this one

**Comment by yzeng25** [comment]
Ok got it!
