### ISSUE TITLE
[Site]:  Add a Social media icons in footer

### ISSUE THREAD

**Issue by Anita-ihuman** [iresty/iresty.github.io#1005]
### Current State

**Description of the current state/issue**:
The APISIX website footer currently lacks a social component that lists the different social media icons for Twitter, LinkedIn, Youtube, and Medium.
**Link to the page**:
https://apisix.apache.org/
**Screenshots (if relevant)**:
<img width="1123" alt="Screenshot 2022-04-05 at 10 04 30" src="https://user-images.githubusercontent.com/62384659/161719904-1aa6ce49-1384-4e9a-8442-cff01d0739c9.png">

### Desired State

**Description of the change you are proposing**:
Add a Social component that will contain icons and links to these platforms

### Would you like to fix this issue?

No. Please assign another contributor

**Comment by SkyeYoung** [comment]
Good idea!

But, what kind of logo should we add?

I often use [the Iconify SVG Logos set](https://icon-sets.iconify.design/logos/). Do you have any other suggestions?

**Comment by Anita-ihuman** [comment]
[the Iconify SVG Logos set](https://icon-sets.iconify.design/logos/) Works just fine.

**Comment by adarrssh** [comment]
I think [the Iconify SVG Logos set ](https://icon-sets.iconify.design/logos/) will do the job for icons.
