### ISSUE TITLE
[Site]: The drop-down box appears as `undefined`

### ISSUE THREAD

**Issue by Chever-John** [iresty/iresty.github.io#1020]
### Current State

**Description of the current state/issue**: When I click on the drop-down box to switch between documents, there will be `undefined` error status

**Link to the page**: https://apisix.apache.org/zh/docs/apisix/getting-started

**Screenshots (if relevant)**: 
<img width="474" alt="image" src="https://user-images.githubusercontent.com/43690894/162920996-f65e6eda-563f-4343-a2a3-866f0fc61394.png">

### Desired State

**Description of the change you are proposing**:

### Would you like to fix this issue?

No. Please assign another contributor

**Comment by SkyeYoung** [comment]
Pls assign this to me, I will fix it.

**Comment by Chever-John** [comment]
I'm sry to say that this problem still exists.

<img width="319" alt="image" src="https://user-images.githubusercontent.com/43690894/163120122-469ef17c-4122-4ef2-908a-0220848655e1.png">
