### ISSUE TITLE
[chore]: In Chinese language, the top navigation bar button needs to be translated into Chinese

### ISSUE THREAD

**Issue by juxianzheng** [iresty/iresty.github.io#1023]
### Current State

**Description of the current state/issue**:In Chinese language, the top navigation bar button needs to be translated into Chinese

**Link to the page**:https://apisix.apache.org/zh/showcase/

**Screenshots (if relevant)**:
<img width="901" alt="image" src="https://user-images.githubusercontent.com/95214263/163103338-0dbf8cd3-1aed-4f54-bc93-e6dafa078ab3.png">

### Desired State

**Description of the change you are proposing**:

### Would you like to fix this issue?

Yes! Count me in

**Comment by SkyeYoung** [comment]
It looks like this issue can be turned off.

cc @guoqqqi @bzp2010 @juzhiyuan
