### ISSUE TITLE
[Site]: drop-down box still exist problem

### ISSUE THREAD

**Issue by Chever-John** [iresty/iresty.github.io#1026]
I'm sry to say that this problem still exists.

<img width="319" alt="image" src="https://user-images.githubusercontent.com/43690894/163120122-469ef17c-4122-4ef2-908a-0220848655e1.png">

_Originally posted by @Chever-John in https://github.com/apache/apisix-website/issues/1020#issuecomment-1097638856_

**Comment by SkyeYoung** [comment]
Assign to me, I'll check it again 😅

**Comment by SkyeYoung** [comment]
I tried, but did not reproduce the problem. Can you give a stable reproduction process please?

**Comment by Chever-John** [comment]
Sry, it is hard to reproduce it. 
I can tell you how to solve this issue temporarily.

Click `F12` and then `Disable cache` in `Network`.
And then `Clear site data` in `Application -> Storage`.

Now refresh the website.

**Comment by SkyeYoung** [comment]
This issue only appears in the Chinese documentation. I've tried fix this in #1029, pls have a look.
