### ISSUE TITLE
chore: Adjusting the page layout

### ISSUE THREAD

**Issue by juxianzheng** [iresty/iresty.github.io#1027]
### Current State

**Description of the current state/issue**:The current layout looks too small, need to adjust the layout to a larger

**Link to the page**:https://apisix.apache.org/zh/showcase/

**Screenshots (if relevant)**:
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/95214263/163146348-230d6a26-bbdf-404a-9324-c36dd1243607.png">

### Desired State

**Description of the change you are proposing**:
Make the layout bigger

### Would you like to fix this issue?

Yes! Count me in

**Comment by SkyeYoung** [comment]
Sry. Can you please tell me why we need this improvement? And what are your goals for improvement? I think this is something that needs to be discussed, rather than just starting to do it.

**Comment by juxianzheng** [comment]
> 对不起。你能告诉我为什么我们需要这种改进吗？您的改进目标是什么？我认为这是需要讨论的事情，而不是刚开始做。

I made a change just now, do you see it like this?

**Comment by SkyeYoung** [comment]
> I made a change just now, do you see it like this?

@juxianzheng I understand. But I think we need to make the logo bigger more than the layout. The larger layout does not make the layout look better.

**Comment by guoqqqi** [comment]
@juxianzheng 
As I recall there are three sections that need to be changed here
- [ ] change the logo to a high-definition 
- [ ] the logo should be unified, for example, Tik-Tok Travel - the black background does not match with others
- [ ] better adjust the page layout? Now it looks too small.

**Comment by SkyeYoung** [comment]
@guoqqqi Hi, for the first and second tasks, we already have the corresponding issues, it's #580.

**Comment by SkyeYoung** [comment]
@juxianzheng Pls create a PR for an issue if possible.

Like I said, pls complete the corresponding changes in #580. 
Also we can discuss whether it is really better to make the layout bigger. :D
