### ISSUE TITLE
chore：Logo should be unified under

### ISSUE THREAD

**Issue by juxianzheng** [iresty/iresty.github.io#1031]
### Current State

**Description of the current state/issue**:The logo should be unified, for example, Tik-Tok Travel - the black background does not match the others

**Link to the page**:https://apisix.apache.org/zh/showcase/

**Screenshots (if relevant)**:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/95214263/163343385-762cf47b-5845-4a61-a5f8-2caff1cfea26.png">

### Desired State

**Description of the change you are proposing**:
The logo should be unified, for example, Tik-Tok Travel - the black background does not match the others

### Would you like to fix this issue?

Yes! Count me in

**Comment by SkyeYoung** [comment]
We already have an issue, this issue is duplicated, please close this. https://github.com/apache/apisix-website/issues/580

**Comment by SkyeYoung** [comment]
Maybe you feel some discouragement, but I still want to tell you, please think more before you do.
