### ISSUE TITLE
[Site]: language switcher is wired on Blog related pages.

### ISSUE THREAD

**Issue by juzhiyuan** [iresty/iresty.github.io#1041]
### Current State

**Description of the current state/issue**:

1. Visit Chinese Blog List: https://apisix.apache.org/zh/blog/
2. In the language switcher, it says "简体中文 Blog" and "English Blog".

![image](https://user-images.githubusercontent.com/2106987/163913936-f4196779-ba36-4fc4-84f6-eec4cd1c2127.png)

### Desired State

**Description of the change you are proposing**:

1. In Chinese mode, it could be "中文博客" & "英文博客"；
2. In English mode, it could be "Chinese" & "English", no need to mention "Blog".

After discussion with @SkyeYoung, the logic is very complicated, so I just added an issue here. Logic: https://github.com/apache/apisix-website/blob/master/website/src/clientModules/amend-lang-switch.js

**Comment by Chever-John** [comment]
I think this feature is pretty pointless.

**Comment by SkyeYoung** [comment]
> I think this feature is pretty much bullshit

you could ask ming

**Comment by juzhiyuan** [comment]
@Chever-John This change belongs to Product policy, which will affect user behavior.

I'm familiar with previous behavior: when I want to read a translated version, I will click the language switcher directly. But now, it changes: when I switch languages, it will return to the Blog list. This could avoid the 404 issues if there has only one language.

But please keep polite in the community, you could share your thoughts on improving the Product, rather than complain. It will not take any good things to the community.

**Comment by SkyeYoung** [comment]
> @Chever-John This change belongs to Product policy, which will affect user behavior.
> 
> I'm familiar with previous behavior: when I want to read a translated version, I will click the language switcher directly. But now, it changes: when I switch languages, it will return to the Blog list. This could avoid the 404 issues if there has only one language.
> 
> But please keep polite in the community, you could share your thoughts on improving the Product, rather than complain. It will not take any good things to the community.

If we have a single blog website, it will be easy to solve this 😅(Maybe)

**Comment by yzeng25** [comment]
Hey @juzhiyuan @SkyeYoung @Chever-John , we don't have the language switch anymore, I think we can close this issue.
