### ISSUE TITLE
[Proposal]: refactor Blog module

### ISSUE THREAD

**Issue by SkyeYoung** [iresty/iresty.github.io#1048]
> This task will be suspended because there are more important things to be done.
> May start this task on July 7.

# Background
Currently, APISIX Website is using the blog feature of Docusaurus, which solved a lot of problems at the beginning.

However, as we have more and more blog posts, we have encountered many problems:

1. #920
2. #945 (Indirect)
3. #1041
4. Search is not good enough (when I need to search for title, category, author...)
5. The user experience of the blog listing page and article page is also not good enough

So it's time to refactor.

# Goals
1. Better user experience (page design, search, etc.)
2. Some better and very necessary features (SEO, i18n, etc.)

# Scheme
We will move the `blog` folder to the root directory, making it the same level as the `website` folder to make it clear that its structure is not related to docusaurus.

Also, limited by the fact that we only own [one domain](//apisix.apache.org), we still need to make sure that the blog folder is in a subdir of the site root after the build, so we have to modify some of the build scripts.

But as for the blog program to be used, we would like to **get some suggestions**. The options that are already under consideration are:

1. [Hexo](//hexo.io/)
2. [Hugo](//gohugo.io/)
3. [Asciidoctor](//asciidoctor.org/)
4. Headless CMS + Next.js

# Time Period 
* This proposal will be closed for comments on May 4. 
* All suggestions will be measured after May 5. 
* ~~And the refactor work will start after June 1.~~

# Other
If you have any suggestions or questions about this, please reply to this issue.

**Comment by juzhiyuan** [comment]
also cc @nfrankel @moonming @navendu-pottekkat

**Comment by pottekkat** [comment]
I would suggest using Hugo. I may be biased because I am a Hugo user in my personal blogs and other projects. Hugo is fast and easy. There are even good themes. It is really easy to configure as well.

One thing we have to make sure is that when we create a new site, we should make sure that the website looks same. Like it should not feel like the blogs are different site than rest of the website.

Before thinking about adding a new site, would it be possible to change the style in Docusaurus itself? It should be customisable I think?

**Comment by nfrankel** [comment]
>But as for the blog program to be used, we would like to get some suggestions. The options that are already under consideration are:
>
>* [Hexo](https://hexo.io/)
>* [Hugo](https://gohugo.io/)
>* [Asciidoctor](https://asciidoctor.org/)

Sorry, Asciidoctor is not a blog engine, it's a format.

I personally use Jekyll. It's in Ruby, it's easy to create plugins even if you don't know Ruby (I did) and the ecosystem is quite large - there's an Asciidoctor integration.

Whatever we choose, we need to make sure such an integration exists.

**Comment by SkyeYoung** [comment]
> > But as for the blog program to be used, we would like to get some suggestions. The options that are already under consideration are:
> > 
> > * [Hexo](https://hexo.io/)
> > * [Hugo](https://gohugo.io/)
> > * [Asciidoctor](https://asciidoctor.org/)
> 
> Sorry, Asciidoctor is not a blog engine, it's a format.
> 
> I personally use Jekyll. It's in Ruby, it's easy to create plugins even if you don't know Ruby (I did) and the ecosystem is quite large - there's an Asciidoctor integration.
> 
> Whatever we choose, we need to make sure such an integration exists.

> Sorry, Asciidoctor is not a blog engine, it's a format.

Emmmm, I think AsciiDoc is a format, and Asciidoctor is a tool chain. (I don't really know it 😅)

But I'm really not familiar with ruby. In fact almost everyone I know is not familiar with ruby (you are the first :D).

In fact, I was very concerned about whether using Ruby would have some impact on our subsequent maintenance. Here are some of my concerns: 

1. It would introduce additional and possibly huge Ruby dependencies in the CI. 
2. Most of the people I know who maintain the front end are not familiar with Ruby, and probably Nodejs and Go have more influence than that.

**Comment by SkyeYoung** [comment]
> One thing we have to make sure is that when we create a new site, we should make sure that the website looks same. Like it should not feel like the blogs are different site than rest of the website.

I was considering doing that, but then realized that it wouldn't work because it don't actually have a way to share a react router with docusaurus (maybe I can, but it would be a pain). Then even if I kept the header and footer, their behavior would be inconsistent with the current behavior in the site (i.e. there would be a refresh).

So I think it's better to treat it as a separate site with separate pages, just under the same domain as the original site. And, such a measure would not only reduce the complexity up front, but would also make it easier to refactor the documentation sites later (they no longer need to be consistent).

**Comment by nfrankel** [comment]
>Emmmm, I think AsciiDoc is a format, and Asciidoctor is a tool chain. (I don't really know it 😅)

Correct.

>I was very concerned about whether using Ruby

You're not using Ruby, you're using Jekyll. You don't need to write code. It's like saying that you need to know PHP to use WordPress.

I won't fight for Jekyll, I'm just saying that the ecosystem is huge and that many plugins are already around. I don't know about Hugo, but if the only argument to use it is that it builds in 5 minutes instead of 10, then it's not a good enough argument.

For the record, my Jkeyll blog of 621 blog posts (as of today) builds in around 10 minutes on GitLab.

**Comment by SkyeYoung** [comment]
> You don't need to write code. It's like saying that you need to know PHP to use WordPress.

In fact, this is the problem, IMO.😅

I've used Wordpress, Ghost, Hexo, Hugo, and my current blog is written by myself using Next.js (which I haven't finished yet). In the process of using them, I sometimes had to modify some of their code (maybe with the help of a plugin system, or hooks or something).

And our current blog module is also implemented by modifying some code (even though they are all JS).

So I think it is necessary to consider whether the code is easy to modify. (Just maybe)

> I won't fight for Jekyll, I'm just saying that the ecosystem is huge and that many plugins are already around.

For various reasons, I didn't use JekylI. The first SSG I used was Hexo, which was popular among people I knew at the time.

But I'm actually open to using Ruby and Jekyll, I like to try things I haven't tried before. And a good ecosystem is obviously a worthwhile point for me to try.

However, we may need to consider it for subsequent maintenance, so I will try it, but most likely will not choose it.

> For the record, my Jkeyll blog of 621 blog posts (as of today) builds in around 10 minutes on GitLab.

Because, I don't know if I'll offend you, I still think it's a bit slow, I wish it had a build time of two minutes or less (Measured by the number of your posts). 😳

**Comment by nfrankel** [comment]
>Because, I don't know if I'll offend you, I still think it's a bit slow, I wish it had a build time of two minutes or less (Measured by the number of your posts). 😳

You don't offend me. My point is, once you reach a couple of minutes, what's the benefit? Either it's close to instant or it's not. For static websites generator, I'm more interested in the richness of the ecosystem.

Because the point is not to write code but to select off-the-shelf components that we only need to configure.

**Comment by SkyeYoung** [comment]
> Either it's close to instant or it's not. For static websites generator, I'm more interested in the richness of the ecosystem.

I can understand that. The metrics that will be measured will include the ecosystems that we may need.

> Because the point is not to write code but to select off-the-shelf components that we only need to configure.

Agree with you.🤝

I'm a lazy person. And the reason I tried so many different blog programs was to have a program that would work without me having to change any code. But as it turns out, I never got what I wanted.😂

Anyway, let's try it all.

**Comment by nfrankel** [comment]
>But as it turns out, I never got what I wanted.😂

Indeed. So we need a list of requirements and check which ecosystem allows us to write the less code in the most comfortable language.

I agree with you about the lack of Ruby skills. From my own personal experience, I'm not a Ruby dev myself but I could write the code that I needed.

**Comment by SkyeYoung** [comment]
cc @guoqqqi @Baoyuantop @yzeng25 Do you have any other suggestions?

**Comment by Baoyuantop** [comment]
Can [Docusaurus Swizzling](https://docusaurus.io/docs/swizzling) meet our needs?

**Comment by SkyeYoung** [comment]
@Baoyuantop No... It is not a long-term solution.

**Comment by yzeng25** [comment]
I am fine with all options, whether changing to one of the frameworks above, or staying in Docusaurus depends on the discussion. 

Can we get some simple demos with Hexo, Hugo, and Asciidoctor? I think discussing this topic without demos is less convincing. 

In addition, changing framework is a huge thing, which is also worth discussing in the mailing list. I am expecting few responses from the mailing list, but you should definitely do a proposal in the mailing list, and guide people who are interested, or want to offer help, into this discussion.

Another problem is to communicate with technical writer and community operations' side. As far as I know, all of @SylviaBABY , @hf400159 , @lijing-21 , and @reeseliu715 **have nearly no previous experience** with Hexo, Hugo, or Asciidoctor. Given that Apache APISIX Summit is hosted in May, and they are going to continuously update the contents, i.e. converting some of the presentations to blogs, I think changing framework could create extra challenges for them. So **when to change** is also an important part for consideration.

The last problem is about the blog contribution guide, once agreed to change framework, some of you need to update that document as well. Not a big deal, but I think it is worth mentioning here.

**Comment by SkyeYoung** [comment]
> I think discussing this topic without demos is less convincing.

Demos will be created after May 5, now just to collect some suggestions. 

> In addition, changing framework is a huge thing, which is also worth discussing in the mailing list. I am expecting few responses from the mailing list, but you should definitely do a proposal in the mailing list, and guide people who are interested, or want to offer help, into this discussion.

I'm not familiar with this area and I'm not sure if I need to send a Proposal to the mailing list, so let me ask @juzhiyuan 

> Another problem is to communicate with technical writer and community operations' side. As far as I know, all of @SylviaBABY , @hf400159 , @lijing-21 , and @reeseliu715 have nearly no previous experience with Hexo, Hugo, or Asciidoctor. 

One of the ideas behind replacing the blog module is to make blogging easier for technical writers. 

> So **when to change** is also an important part for consideration.

I will assist technical writers in migrating to the new program at a suitable time. **In fact the whole refactoring may not be completed until the end of May.**

> The last problem is about the blog contribution guide, once agreed to change framework, some of you need to update that document as well. Not a big deal, but I think it is worth mentioning here.

Of course it will.

**Comment by SkyeYoung** [comment]
> Demos will be created after May 5, now just to collect some suggestions.

I updated the Time Period part.

**Comment by SkyeYoung** [comment]
Recently, I found a way to build a blog: a headless CMS + a SSG like Next.js, and I'm going to add this to the consideration.

**Comment by SkyeYoung** [comment]
The start of the refactoring work was delayed until after June 1, due to some real-life arrangements

**Comment by juzhiyuan** [comment]
> Recently, I found a way to build a blog: a headless CMS + a SSG like Next.js, and I'm going to add this to the consideration.

You mean https://github.com/tinacms/tinacms this one? cc @membphis

**Comment by SkyeYoung** [comment]
> > Recently, I found a way to build a blog: a headless CMS + a SSG like Next.js, and I'm going to add this to the consideration.
> 
> You mean [tinacms/tinacms](https://github.com/tinacms/tinacms) this one? cc @membphis

Yeah, we need to try

**Comment by SkyeYoung** [comment]
Hi folks, due to some things in my reality, this work may need to be further delayed and could be started probably by mid-June

**Comment by yzeng25** [comment]
It is 1 day away from July. @SkyeYoung , would you extend the timeline and update this issue soon?

**Comment by SkyeYoung** [comment]
> It is 1 day away from July. @SkyeYoung , would you extend the timeline and update this issue soon?

I may not be able to start soon because there are more important things that need to be done, but I will re-plan my time.
Let's mark this task as paused.

**Comment by yzeng25** [comment]
> > It is 1 day away from July. @SkyeYoung , would you extend the timeline and update this issue soon?
> 
> I may not be able to start soon because there are more important things that need to be done, but I will re-plan my time. Let's mark this task as paused.

Great, keep us updated when you find time for this.

**Comment by SkyeYoung** [comment]
I'm working on this issue.
However, due to some project considerations, I decided not to switch to another SSG, but to modify the original Docusaurus. You can already see the changes in PR https://github.com/apache/apisix-website/pull/1218.
And I'm going to work on the UI design part this week.

**Comment by SkyeYoung** [comment]
I'm working on UI design, and I think it's making good progress.

For the convenience of tracking progress, I list the PRs I submitted below.

* https://github.com/apache/apisix-website/pull/1236
* https://github.com/apache/apisix-website/pull/1238
* https://github.com/apache/apisix-website/pull/1240
* https://github.com/apache/apisix-website/pull/1241
* https://github.com/apache/apisix-website/pull/1251
* https://github.com/apache/apisix-website/pull/1255
* https://github.com/apache/apisix-website/pull/1260
* https://github.com/apache/apisix-website/pull/1262
