### ISSUE TITLE
link errors: I must point out that we have two problems with checking links

### ISSUE THREAD

**Issue by Chever-John** [iresty/iresty.github.io#1050]
I think this issue can be closed since we already have a link checker, and the question of whether there is a problem with the link checker in operation should be discussed in a separate issue.

_Originally posted by @SkyeYoung in https://github.com/apache/apisix-website/issues/1047#issuecomment-1107679989_

# Background

Hi, this problem is from a user's question from IM. He asked, "why this link is pointed to 'page not found". You can click this [link](https://apisix.apache.org/docs/apisix/next/FAQ/#:~:text=You%20can%20learn%20more%20about%20hot%20reloading%20of%20Plugins%20here.) here to reproduce this question.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/43690894/164952329-4145ec6c-7fb7-4fac-993d-10fdf1f665cc.png">

## **Then he will get this page!** (In the language state of English)

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/43690894/164952422-45dd475b-7cf2-402b-8e54-0fe909129e0b.png">

## **Then he will get this page!** (In the language state of Chinese)

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/43690894/164953252-ff310e7d-7bf6-44d2-a78b-41383a2370f4.png">

# How to solve this problem?

Of course, some people attribute this problem to the CI. 
They think that we have to add the "**link checker**", however, the truth is that we already have this CI tool. (refer to this [link](https://github.com/apache/apisix-website/actions/runs/2211305783))

**So why do we still have this broken link problem even after having a link checking tool?**

I must point out two questions we have!

1. This is a historical problem. We have done many document refactorings to optimize the reading experience of the documents, and thus many broken links have been left behind. And the documentation team was not aware of the problem.
2. The site's link checking tool does not fully meet our needs. After my review, the tool also reported off-site links, which led to a very high number of links being misreported. (refer to this [link](https://github.com/apache/apisix-website/actions/runs/2211305783#:~:text=by%20humans.txt-,Artifacts,-Produced%20during%20runtime))

cc @navendu-pottekkat @SkyeYoung @juzhiyuan @hf400159 

If we solve these two problems, there will be no more problems with broken links.

**Comment by SkyeYoung** [comment]
@Chever-John Hi, pls check and specify which links are problematic. I don't think we should waste our time with everyone checking over the links.

Off-site links are certainly something that needs to be checked, and we need to make sure that every link in the document is valid as much as possible. All that needs to be improved is the way in which it is checked.

**Comment by Chever-John** [comment]
@SkyeYoung  Off-site links are certainly something that needs to be checked, but they should not be considered a "Fail".

<img width="631" alt="image" src="https://user-images.githubusercontent.com/43690894/164957114-7d93da45-c861-4af8-b19d-52e9198094d8.png">


Also, this link is correct, and it is reported as a "Fail".

<img width="833" alt="image" src="https://user-images.githubusercontent.com/43690894/164957180-26f28005-22c8-486f-962c-e3d3e167c26e.png">

These pictures are from the `brokenList.json` autogenerated by the link-checker tool.
You can click this [link](https://github.com/apache/apisix-website/actions/runs/2211305783#:~:text=Size-,broken%2Dlinks.json,-484%20KB) for the `brokenList.json` and download it to verify.
 
It seems that the link-checker does not work.

**Comment by SkyeYoung** [comment]
> but they should not be considered a "Fail".

Current, we just have _Fail_ state, so it's what need to improved but not a problem.

> Also, this link is correct, and it is reported as a "Fail".

I will check this.

**Comment by Chever-John** [comment]
feel free to reopen this issue if you need it.
