### ISSUE TITLE
[Site]: chore the poster modal

### ISSUE THREAD

**Issue by guoqqqi** [iresty/iresty.github.io#1057]
### Current State

1. The poster is no longer displayed after one click.
2. When clicked, the `SHOW_EVENT_ENTRY` variable is stored in `Local Storage`

![image](https://user-images.githubusercontent.com/72343596/165210681-7a85582d-9a57-4665-aee4-ed04a25fa527.png)

### Desired State

**Description of the change you are proposing**:
1. Support links in different Chinese and English languages
2. After closing the poster, support for each refresh throw will show
- change `Local storage` to `Session storage`
3. Chinese state poster to `https://apisix.apache.org/zh/blog/2022/04/12/apisix-summit-asia-2022`
4. English state poster to `https://apisix-summit.org/`

![image](https://user-images.githubusercontent.com/72343596/165210764-7928a696-c09e-4214-a2e4-98d0e5827856.png)

**Comment by hanzhenfang** [comment]
@guoqqqi 

let me try.

**Comment by SkyeYoung** [comment]
@hanzhenfang sorry, I fixed this 😅
