### ISSUE TITLE
[Site]: Some links are broken due to archived historical documents.

### ISSUE THREAD

**Issue by juzhiyuan** [iresty/iresty.github.io#1066]
### Current State

**Description of the current state/issue**:

When I search `apisix introspection_endpoint` by Google, the first item is broken.

**Link to the page**:

https://apisix.apache.org/docs/apisix/2.6/plugins/openid-connect/

**Screenshots (if relevant)**:

![image](https://user-images.githubusercontent.com/2106987/167049004-14ad21d1-ffe7-45e2-b858-eda7b8e9778a.png)

### Desired State

**Description of the change you are proposing**:

I know it's because of https://github.com/apache/apisix-website/pull/1030, we archived history documents to avoid unnecessary builds, but it leads to some links 404.

If we want to fix this problem:
1. Server redirects: but the ASF Infra can't set up specific rules for this site.
2. Put history documents in the asf-site branch and don't use force-push when publishing.
3. Update sitemap.

### Would you like to fix this issue?

No. Please assign another contributor

**Comment by juzhiyuan** [comment]
**Update**

Refer to EChart's htaccess configuration https://github.com/apache/echarts-website/blob/asf-site/.htaccess

**Comment by SkyeYoung** [comment]
I'd like to fix this, pls assign this to me.
