### ISSUE TITLE
[Docs]: translate the content under the `general` directory

### ISSUE THREAD

**Issue by guitu168** [iresty/iresty.github.io#1077]
### Current State

**Description of the current state/issue**:
Translate the contents of the `general` directory, including: 
[join](https://github.com/apache/apisix-website/blob/master/website/docs/general/join.md)
[submit-issue](https://github.com/apache/apisix-website/blob/master/website/docs/general/submit-issue.md)
[security-guide](https://github.com/apache/apisix-website/blob/master/website/docs/general/security-guide.md)
[committer-guide](https://github.com/apache/apisix-website/blob/master/website/docs/general/committer-guide.md.) 

For documentation style and content specification, make sure to read [中文文档写作指南](https://apisix.apache.org/zh/docs/general/documentation-style-guide/) first before submitting content.

**Comment by lunarwhite** [comment]
Hi, I'd like to work on this and then open a PR.
