### ISSUE TITLE
[Docs]: translate the docs under the `contribute to APISIX` directory 

### ISSUE THREAD

**Issue by guitu168** [iresty/iresty.github.io#1078]
### Current State

**Description of the current state/issue**:
Translate the contents of the `Contribute to APISIX` directory, including: 
[contributor-guide](https://github.com/apache/apisix-website/blob/master/website/docs/general/contributor-guide.md)
[blog-contributing-guide](https://github.com/apache/apisix-website/blob/master/website/docs/general/blog-contributing-guide.md)

For documentation style, please refer to [中文文档写作指南](https://apisix.apache.org/zh/docs/general/documentation-style-guide/).

**Comment by lawrshen** [comment]
hi, I want to do this job.

**Comment by SkyeYoung** [comment]
Recommend adding **translation** tag

**Comment by lawrshen** [comment]
[blog-contributing-guide](https://github.com/apache/apisix-website/blob/master/website/docs/general/blog-contributing-guide.md) in progress, I will complete it recently
