### ISSUE TITLE
[Site]: Add lightbox to display images

### ISSUE THREAD

**Issue by pottekkat** [iresty/iresty.github.io#1084]
### Current State

**Description of the current state/issue**:

Currently, to zoom in to an image, users have to open just the image in a new tab.

This makes it difficult to understand large diagrams.

### Desired State

**Description of the change you are proposing**:

Instead, add a lightbox feature that would open up a modal that the users can interact with when clicking an image.

Here is an example of a lightbox: https://www.lightgalleryjs.com/

### Would you like to fix this issue?

No. Please assign another contributor

**Comment by pottekkat** [comment]
@SkyeYoung Here you go.

**Comment by SkyeYoung** [comment]
@navendu-pottekkat  Hi, I think https://github.com/rpearce/image-zoom may be more appropriate. But it will prevent us from getting the image directly (by right clicking the mouse), do you think this will have a very big impact?

cc @juzhiyuan

**Comment by SkyeYoung** [comment]
Or this one? https://github.com/brycedorn/react-intense

**Comment by pottekkat** [comment]
> @navendu-pottekkat Hi, I think [rpearce/image-zoom](https://github.com/rpearce/image-zoom) may be more appropriate. But it will prevent us from getting the image directly (by right clicking the mouse), do you think this will have a very big impact?
> 
> cc @juzhiyuan

This looks quite good. It may be a problem to not be able to right-click and save. Especially if you want to share something on a different platform.

> Or this one? [brycedorn/react-intense](https://github.com/brycedorn/react-intense)

This feels kind of bloated IMO. I think we can keep it as simple as possible.

Others, please suggest!

**Comment by SkyeYoung** [comment]
I am looking for other dependencies that can be used. 😮‍💨😊

**Comment by SkyeYoung** [comment]
https://github.com/react-component/image This one! It looks great!

**Comment by juzhiyuan** [comment]
> https://github.com/react-component/image This one! It looks great!

Ah! I just have a try and it's good to me!

**Comment by pottekkat** [comment]
Looks good!

**Comment by SkyeYoung** [comment]
> Ah! I just have a try and it's good to me!
> Looks good!

I will start this work as soon as possible😊
