### ISSUE TITLE
[Site]: Mobile can not load the home page style

### ISSUE THREAD

**Issue by oil-oil** [iresty/iresty.github.io#1085]
### Current State

When I open the apisix website from my phone, the home page is gray and the collapsed bar in the upper left corner is not clickable

![image](https://user-images.githubusercontent.com/57465570/167996169-47a6cb74-b0df-4475-95cd-b529fb599d1e.png)

### Desired State

**Description of the change you are proposing**:
Load the page normally, just like debugging in a computer browser
<img width="432" alt="image" src="https://user-images.githubusercontent.com/57465570/167996409-812da4de-1dde-41fc-ba63-6141ab018134.png">

**Comment by SkyeYoung** [comment]
This is because we don't have a CDN in China anymore, you may need a proxy software.

**Comment by SkyeYoung** [comment]
cc @juzhiyuan

**Comment by juzhiyuan** [comment]
After jsDelivr is banned by GFW, there have been no public better ways to accelerate static files so far. I will close this issue and link it to another open one.

https://github.com/apache/apisix-website/issues/675
