### ISSUE TITLE
[Site]: Text doesn't align in chinese language

### ISSUE THREAD

**Issue by barchielAbyss** [iresty/iresty.github.io#1103]
### Current State

**Description of the current state/issue**:
I want set `text-align` style fix it, but I'm not sure it's compatible with all other translation languages.

The problem of Chinese here is 3-4 bytes, so the width of the text cannot be matched. I want to use css to solve it, but this will lead to a problem that it may not have stable horizontal text spacing (other languages will be Affect)

**Link to the page**:
https://apisix.apache.org/zh/

**Screenshots (if relevant)**:
![image](https://user-images.githubusercontent.com/23497322/169441563-ed35ecf0-634e-4fcf-a0e7-bfe82950f4e3.png)

### Desired State

**Description of the change you are proposing**:
![image](https://user-images.githubusercontent.com/23497322/169441621-22a11d15-a22a-4914-8a4b-0114eaf8f267.png)

### Would you like to fix this issue?

Yes! Count me in

**Comment by barchielAbyss** [comment]
i tried it, look like it is not good idea

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/23497322/169543558-75b12e15-798c-4521-94a7-7e3110513827.png">

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/23497322/169543642-21a16913-bef1-4c0c-99f5-2f3d47ae3d9d.png">

**Comment by barchielAbyss** [comment]
I will close this issue on May 22 because it is not a good proposal.

**Comment by SkyeYoung** [comment]
I think it's a very good idea.

We can set the style of the Chinese and English fonts separately, which is what I intend to do, but there may be some difficulties.

**Comment by barchielAbyss** [comment]
> I think it's a very good idea.
> 
> We can set the style of the Chinese and English fonts separately, which is what I intend to do, but there may be some difficulties.

I will close this pr first, and change my mind to solve this problem. Obviously, this style sheet attribute does not apply to all languages.
