### ISSUE TITLE
[Site][Discussion]: maintain a VSCode config dir

### ISSUE THREAD

**Issue by SkyeYoung** [iresty/iresty.github.io#1110]
> Sorry, I need to point out some problems.
> 
> Before you do something, please consider as much as possible whether we really need these improvements, and if you don't know, please create a proposal.
> 
> For example, do we really need a configuration for vscode? Does your configuration work for everyone? I think the answer is obviously no.
> 
> For example, does the addition of jest make sense? Does it cover all use cases that need to be tested?
> 
> There are other problems that I don't want to enumerate.
> 
> Also, I recommend doing one thing per PR, not everything.

I understand your concern about why the `vscode` folder needs to be uploaded. It is because everyone may modify the code of this project, so you should provide a basic configuration of the vscode for this project, which may increase Your code review work, see if anyone has modified this file, but the advantage of this is that everyone will have a default configuration in the project's workspace, which can greatly reduce their configuration of this project time

_Originally posted by @barchielAbyss in https://github.com/apache/apisix-website/issues/1109#issuecomment-1133816229_

**Comment by SkyeYoung** [comment]
@barchielAbyss I accept this change and you can create a Proposal if needed.

But I also want to point out that if we add it, then we need to make sure that the vscode configuration is maintained for a long time.

In addition to this, I am very concerned that people will want to add configurations for various editors or IDEs such as Emacs, Vim, Neovim, Webstorm, etc.

I have previously considered adding some of the recommended vscode plugins to the README, so if you want to do that, please maintain an additional document for newbies. (It is best to create a separate document and add a link to the README.)

**Comment by barchielAbyss** [comment]
> @barchielAbyss I accept this change and you can create a Proposal if needed.
> 
> But I also want to point out that if we add it, then we need to make sure that the vscode configuration is maintained for a long time.
> 
> In addition to this, I am very concerned that people will want to add configurations for various editors or IDEs such as Emacs, Vim, Neovim, Webstorm, etc.
> 
> I have previously considered adding some of the recommended vscode plugins to the README, so if you want to do that, please maintain an additional document for newbies. (It is best to create a separate document and add a link to the README.)

I don't think it's too much of a problem to maintain documentation, but they need to be found quickly, So which README should it be placed in? I think it is <Root>/README.md, what do you think? Wouldn't it be a bit strange, what was written there was a project introduction

**Comment by SkyeYoung** [comment]
IMO, It’s okay.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Barchiel ***@***.***>
发送时间: Sunday, May 22, 2022 2:08:02 PM
收件人: apache/apisix-website ***@***.***>
抄送: Young ***@***.***>; Author ***@***.***>
主题: Re: [apache/apisix-website] [Site][Discussion]: maintain a VSCode config dir (Issue #1110)


@barchielAbyss<https://github.com/barchielAbyss> I accept this change and you can create a Proposal if needed.

But I also want to point out that if we add it, then we need to make sure that the vscode configuration is maintained for a long time.

In addition to this, I am very concerned that people will want to add configurations for various editors or IDEs such as Emacs, Vim, Neovim, Webstorm, etc.

I have previously considered adding some of the recommended vscode plugins to the README, so if you want to do that, please maintain an additional document for newbies. (It is best to create a separate document and add a link to the README.)

I don't think it's too much of a problem to maintain documentation, but they need to be found quickly, So which README should it be placed in? I think it is /README.md, what do you think? Wouldn't it be a bit strange, what was written there was a project introduction

―

**Comment by barchielAbyss** [comment]
> IMO, It’s okay.

I append to `README.md` file, please check https://github.com/apache/apisix-website/pull/1113
