### ISSUE TITLE
[Site][Discussion]: remove raw-loader, add type hint

### ISSUE THREAD

**Issue by SkyeYoung** [iresty/iresty.github.io#1111]
> > remove raw-loader package, change 2 es module export Object
> 
> I also want to remove rawloader, but I don't think it should be done this way.
> 
> We should configure webpack5 directly, this is a capability that docusaurus has not provided so far.
> 
> I'm making some efforts to make our dependency on docusaurus as little as possible. But it's a step-by-step process, not removing configurations that we can't handle at the moment

emm, docusaurus can configure it,  maybe u can see [there](https://github.com/algolia/docsearch-website/blob/master/plugins/my-loaders/index.js),

and `docusaurus.config.js` add
```
plugins: ['your-plugins']
```

seted webpack5 after,  will corrects typescript checks,

I try 2 add, but it is not work
```
// typings/index.d.ts

declare module '*.txt' {
  const content: string;
  export default content;
}

declare module '*.vert' {
  const content: string;
  export default content;
}

declare module '*.frag' {
  const content: string;
  export default content;
}
```

_Originally posted by @barchielAbyss in https://github.com/apache/apisix-website/issues/1109#issuecomment-1133814629_

**Comment by SkyeYoung** [comment]
@barchielAbyss I may have misrepresented it before, but actually, if you have been following docusaurus' PRs and issues, you will see that they are trying to work on this. And we are using an older version of docusaurus, and I plan to do a migration when their version is stable, so I am not going to do this for now.

In the meantime, I'd say the original format gives some code hints in the IDE or editor, but conversion to strings does not, which is why I personally don't accept such a modification.

**Comment by barchielAbyss** [comment]
> @barchielAbyss I may have misrepresented it before, but actually, if you have been following docusaurus' PRs and issues, you will see that they are trying to work on this. And we are using an older version of docusaurus, and I plan to do a migration when their version is stable, so I am not going to do this for now.
> 
> In the meantime, I'd say the original format gives some code hints in the IDE or editor, but conversion to strings does not, which is why I personally don't accept such a modification.

Okay, your consideration is right, this PR has many problems https://github.com/apache/apisix-website/pull/1109, I will extract the vscode part into md, and roll back the other parts

**Comment by SkyeYoung** [comment]
What I think is that if we maintain, we must include vscode configuration files and related documents at the same time.

________________________________
发件人: Barchiel ***@***.***>
发送时间: Sunday, May 22, 2022 1:57:44 PM
收件人: apache/apisix-website ***@***.***>
抄送: Young ***@***.***>; Author ***@***.***>
主题: Re: [apache/apisix-website] [Site][Discussion]: remove raw-loader, add type hint (Issue #1111)


@barchielAbyss<https://github.com/barchielAbyss> I may have misrepresented it before, but actually, if you have been following docusaurus' PRs and issues, you will see that they are trying to work on this. And we are using an older version of docusaurus, and I plan to do a migration when their version is stable, so I am not going to do this for now.

In the meantime, I'd say the original format gives some code hints in the IDE or editor, but conversion to strings does not, which is why I personally don't accept such a modification.

Okay, your consideration is right, this PR has many problems #1109<https://github.com/apache/apisix-website/pull/1109>, I will extract the vscode part into md, and roll back the other parts

―
