### ISSUE TITLE
[Site][Discussion]: use jest as a testing tool

### ISSUE THREAD

**Issue by SkyeYoung** [iresty/iresty.github.io#1112]
> Hi @barchielAbyss, as @SkyeYoung said:
> 
> 1. We should submit proposals to explain why we need this new feature and how to implement it before submitting PRs, or this project will lose control and become a hodgepodge.
> 2. If most people like your proposal and say "Yes", you could start contributing codes, but you need one PR to do one Thing.
> 
> > added the test framework jest
> 
> I'm not clear why we need Jest to test pages 😂 This is more like a "Marketing" project than an "Application" project.

When I write any script, I have the habit of writing test cases first, if you think it is not applicable in this project, I can delete it first

_Originally posted by @barchielAbyss in https://github.com/apache/apisix-website/issues/1109#issuecomment-1133816405_

**Comment by SkyeYoung** [comment]
@barchielAbyss For a current work in the site, if we need to add tests, then the more important thing is to add e2e tests rather than unit tests.

Of course no matter which test is added, if it is added, we need to ensure its coverage.

Also, I should point out that the site is in the midst of a major restructuring and even if tests are added, they will need to be modified or removed soon.

**Comment by barchielAbyss** [comment]
> @barchielAbyss For a current work in the site, if we need to add tests, then the more important thing is to add e2e tests rather than unit tests.
> 
> Of course no matter which test is added, if it is added, we need to ensure its coverage.
> 
> Also, I should point out that the site is in the midst of a major restructuring and even if tests are added, they will need to be modified or removed soon.

oh, maybe i need add cypress in this project
