### ISSUE TITLE
[Site][Page: Landing]: fix open source promo block

### ISSUE THREAD

**Issue by SkyeYoung** [iresty/iresty.github.io#1143]
### Current State

**Description of the current state/issue**:
1. No sound in the video
2. Poor video quality after full screen in the player
3. Need to replace the video source with Bobur's video
4. Unable to access YouTube in China

**Link to the page**:
https://apisix.apache.org/#:~:text=Learn%20from%20developers

**Screenshots (if relevant)**:
<img width="2152" alt="image" src="https://user-images.githubusercontent.com/48400568/172754206-820e80b5-3d25-4b24-8153-9ea25508edf9.png">

### Desired State

**Description of the change you are proposing**:
1. Replace video source
2. Replace the Youtube link in the Chinese page
3. May need to replace video tags with third-party dependency libraries

### Would you like to fix this issue?

Yes! Count me in

cc @juzhiyuan @moonming

**Comment by juzhiyuan** [comment]
Please use https://space.bilibili.com/551921247 in Chinese page :)

**Comment by SkyeYoung** [comment]
> Please use [space.bilibili.com/551921247](https://space.bilibili.com/551921247) in Chinese page :)

I've added, pls check https://github.com/apache/apisix-website/pull/1146
