### ISSUE TITLE
[Docs]: Replace Chinese pictures that appear in English articles

### ISSUE THREAD

**Issue by SylviaBABY** [iresty/iresty.github.io#1153]
### Current State

**Description of the current state/issue**:
In many previous blogs, because there was no English processing of pictures at that time, Chinese pictures were still used in the English version of many articles.

**Link to the page**:
- ~~https://apisix.apache.org/blog/2022/01/21/apisix-xrpc-details-and-miltilingual~~ done in https://github.com/apache/apisix-website/pull/1216
- ~~https://apisix.apache.org/blog/2022/06/14/automated-operation-base-apache-apisix~~ done in https://github.com/apache/apisix-website/pull/1242
- ~~https://apisix.apache.org/blog/2022/06/14/beeto-with-apache-apisix（https://github.com/apache/apisix-website/pull/1199)~~
- ~~https://apisix.apache.org/blog/2022/06/14/how-mse-supports-canary-release-with-apache-apisix~~ done in https://github.com/apache/apisix-website/pull/1242 
- ~~https://apisix.apache.org/blog/2022/06/14/xueqiu-with-apache-apisix~~ done in https://github.com/apache/apisix-website/pull/1242~~ done in https://github.com/apache/apisix-website/pull/1242

**Screenshots (if relevant)**:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/39793568/173522915-1b8042cc-9fa8-4615-b939-458271922dc0.png">

### Desired State

**Description of the change you are proposing**:
<img width="759" alt="image" src="https://user-images.githubusercontent.com/39793568/173523142-4b9579e3-3c33-47f0-8cf4-c847b5ff2771.png">

In fact, we have batch-processed pictures once before, but there are still some pictures that have this phenomenon. We will find time to deal with it later

### Would you like to fix this issue?

Yes! Count me in

**Comment by yzeng25** [comment]
Pictures in https://apisix.apache.org/blog/2022/01/21/apisix-xrpc-details-and-miltilingual are done. I will create a pull request afterwards.

Meanwhile, I need the cdn address to upload them, @SylviaBABY @juzhiyuan .

![1_new](https://user-images.githubusercontent.com/36651058/179175317-5cf30a8b-aac2-4538-b9a9-27f99d8d13db.png)
![2_new](https://user-images.githubusercontent.com/36651058/179175336-3a229407-a9ac-418e-9bde-a48f4a42e056.png)
![3_new](https://user-images.githubusercontent.com/36651058/179175341-dfae292d-3aa2-42ed-a306-c87c47b5ace2.png)

**Comment by SylviaBABY** [comment]
@yzeng25 you can use this link(as your photo order)

1. https://static.apiseven.com/2022/blog/0121/179175317-5cf30a8b-aac2-4538-b9a9-27f99d8d13db.png
2. https://static.apiseven.com/2022/blog/0121/179175336-3a229407-a9ac-418e-9bde-a48f4a42e056.png
3. https://static.apiseven.com/2022/blog/0121/179175341-dfae292d-3aa2-42ed-a306-c87c47b5ace2.png

**Comment by yzeng25** [comment]
> @yzeng25 you can use this link(as your photo order)
> 
> 1. https://static.apiseven.com/2022/blog/0121/179175317-5cf30a8b-aac2-4538-b9a9-27f99d8d13db.png
> 2. https://static.apiseven.com/2022/blog/0121/179175336-3a229407-a9ac-418e-9bde-a48f4a42e056.png
> 3. https://static.apiseven.com/2022/blog/0121/179175341-dfae292d-3aa2-42ed-a306-c87c47b5ace2.png

Got it, see https://github.com/apache/apisix-website/pull/1216

**Comment by SkyeYoung** [comment]
Relate #792

**Comment by yzeng25** [comment]
All pictures are replaced in https://github.com/apache/apisix-website/pull/1216 and https://github.com/apache/apisix-website/pull/1242.

For issue https://github.com/apache/apisix-website/issues/792, The one and only picture is already in English. I don't think we can do much about the UI screenshots modifications. 

Unless some of you can:

1. Get in touch with Haili Zhang, and ask him to provide a copy of these screenshots in English;
2. Or build that specific version of KubeSphere on your own, just to get some screenshots.
3. Or translate every phrase/word/sentence on the existing pictures on your own.

All approaches are too complicated and time-consuming.

I'd suggest leave it as it is, and close both https://github.com/apache/apisix-website/issues/792 and this issue.

Making sure the upcoming blogs are using screenshots/images in English is fair enough. Putting efforts in generating new blogs from the upcoming ApacheCon Asia is a wiser decision.

cc @SylviaBABY @SkyeYoung @juzhiyuan
