### ISSUE TITLE
[Docs]: Need to update event page

### ISSUE THREAD

**Issue by yzeng25** [iresty/iresty.github.io#1159]
### Current State

**Description of the current state/issue**:

1. The "Upcoming" section of this page is not upcoming anymore, need to update them into past events.
2. As discussed in mailing list, I would suggest adding the Apache APISIX Meetup - China Nanjing station into the "Upcoming" section.

After this modification, the event page should look like:

```
Upcoming

   Meetup

Past

   Conferences

   Workshops

   Meetups

```

**Link to the page**:

https://apisix.apache.org/docs/general/events/

**Screenshots (if relevant)**:

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/36651058/174708985-bdb89a91-dab8-4b82-8a02-64b21e312af3.png">

### Desired State

**Description of the change you are proposing**:

Events should be up to date.

### Would you like to fix this issue?

No. Please assign another contributor

**Comment by yzeng25** [comment]
@wang-yeliang @juzhiyuan @Boburmirzo please take a look when available, thanks!

**Comment by Boburmirzo** [comment]
@yzeng25 Yes, I usually update it every week and will remove passed events soon.

**Comment by Boburmirzo** [comment]
@yzeng25 I think nobody will be interested in past events so we need to update the page more frequently and that's all.

I added China meetup too.

**Comment by yzeng25** [comment]
> @yzeng25 I think nobody will be interested in past events so we need to update the page more frequently and that's all.
> 
> I added China meetup too.

Yeah definitely. Thank you.
