### ISSUE TITLE
[Site]: Can not access to two important link

### ISSUE THREAD

**Issue by Chever-John** [iresty/iresty.github.io#1197]
### Current State

**Description of the current state/issue**:

Click the links as follows and you will know.

**Link to the page**:

https://apisix.apache.org/docs/apisix/FAQ/#:~:text=You%20can%20find%20more%20answers%20on%3A

**Screenshots (if relevant)**:

![image](https://user-images.githubusercontent.com/43690894/177905747-fe811e5a-fd98-4092-817a-880e665cac1c.png)

### Desired State

**Description of the change you are proposing**:

you know what I want~

**Comment by yzeng25** [comment]
Hi @Chever-John ,

1. All links in this sections work out just fine, I checked them just now.

   <img width="773" alt="image" src="https://user-images.githubusercontent.com/36651058/178179895-26725dbf-5cbb-434a-97d2-030982d296f1.png">

2. This is related to [APISIX's main repo](https://github.com/apache/apisix), as the sources are in there. Even if this is really an issue, you should open it there.

**Comment by Chever-John** [comment]
@yzeng25 Hi~

An interesting discovery, when I "ctrl + click" the link, everything is OK. However, when I just click on this link, the problem arises.

Two different actions will produce two different results.

**Comment by yzeng25** [comment]
Nope, both ways are working well.

And I don't see anything wrong in the source file.

<img width="982" alt="image" src="https://user-images.githubusercontent.com/36651058/178181516-d773e441-3856-4afd-8db2-3d91a24d1542.png">

**Comment by yzeng25** [comment]
@Chever-John ok it works in the `next` version but **not** in the `2.14` version.

**Comment by Chever-John** [comment]
Yeah, I have no problem now.

Thanks so much~
