### ISSUE TITLE
doc: update Blog Contribution guidelines

### ISSUE THREAD

**Issue by juzhiyuan** [iresty/iresty.github.io#1239]
Hi, some guidelines[1] are out-of-date here after adjusting this repo's structure by @SkyeYoung.

Please update them to the latest status. 😉

[1] https://apisix.apache.org/docs/general/blog/

**Comment by guitu168** [comment]
hi, I've updated it. https://github.com/apache/apisix-website/pull/1287/. you can close this issue.
