### ISSUE TITLE
[Site]: search result throws 404 by default

### ISSUE THREAD

**Issue by juzhiyuan** [iresty/iresty.github.io#1253]
### Current State

**Description of the current state/issue**:

1. Visit http://apisix.apache.org/
2. Search a keyword like `Prometheus` and click the first result
3. 404 occurred.
4. Refresh page, it works as expected.

**Link to the page**:

https://apisix.apache.org/blog/2021/12/13/monitor-apisix-ingress-controller-with-prometheus/ 

**Screenshots (if relevant)**:

![image](https://user-images.githubusercontent.com/2106987/182025921-911c7f2e-362d-411f-a400-a1918750a0b8.png)

### Desired State

**Description of the change you are proposing**:

Only showing 404 when that page doesn't exist indeed.

**Comment by juzhiyuan** [comment]
Hey @SkyeYoung @guoqqqi, this issue still occurs 🤣 Please have a double check

**Comment by guoqqqi** [comment]
I've just tried it and I'm not reproducing it here, do you still have this problem on your end?
