### ISSUE TITLE
[Site]: Improving visibility of the Blog page

### ISSUE THREAD

**Issue by BhavyaT-135** [iresty/iresty.github.io#1308]
### Current State

**Description of the current state/issue**:
The Blog page contains all the blogs listed in order. When switching to dark mode, the title and description of individual blogs are not visible properly because of the color combination.

**Link to the page**:
https://apisix.apache.org/blog/

**Screenshots (if relevant)**:
![image](https://user-images.githubusercontent.com/55613637/188128822-27f4ca24-c0b4-4d37-b520-0145daf90189.png)

### Desired State

**Description of the change you are proposing**:
Fixing the color scheme of the page would improve the visibility of the page and would be beneficial for the SEO of the website.

### Would you like to fix this issue?

Yes! Count me in

**Comment by BhavyaT-135** [comment]
Hi @juzhiyuan @yzeng25, could you kindly take a look at this issue and let me know if it's relevant? 😊 

Also, I noticed that while visiting pages such as [Blog](https://apisix.apache.org/blog/), [Case Studies](https://apisix.apache.org/blog/tags/case-studies/), [Downloads](https://apisix.apache.org/downloads/), etc., the button to toggle the theme is not available in the header. So, every time I need to toggle themes, I have to navigate back to the pages where it is available.  Would it be helpful if the button appears on every page and has a fixed position in the header?

**Comment by juzhiyuan** [comment]
Hi @SkyeYoung, can you check with @BhavyaT-135?

**Comment by yzeng25** [comment]
Yeah we need a different set of colors for dark mode, and the mode switch button everywhere. Or disable the dark mode to avoid this problem.

**Comment by SkyeYoung** [comment]
> Also, I noticed that while visiting pages such as [Blog](https://apisix.apache.org/blog/), [Case Studies](https://apisix.apache.org/blog/tags/case-studies/), [Downloads](https://apisix.apache.org/downloads/), etc., the button to toggle the theme is not available in the header. So, every time I need to toggle themes, I have to navigate back to the pages where it is available. Would it be helpful if the button appears on every page and has a fixed position in the header?

@BhavyaT-135 The decision to remove the color mode toggle button on these pages was made by a previous contributor to these pages, and I kept those when I made changes to the site structure.

My thoughts are the same as yours, I would like to bring back the color toggle button to these pages, but I don't have enough time and energy to do this at the moment. 😞 

Please give me some time, maybe I will be free to finish this. 😸

**Comment by BhavyaT-135** [comment]
Sure @SkyeYoung, take your time! 😄

**Comment by mys1024** [comment]
Hi, I'm dealing with this problem in #1359 😊
