### ISSUE TITLE
[Docs]: Default documentation is for Beta

### ISSUE THREAD

**Issue by nfrankel** [iresty/iresty.github.io#1374]
### Current State

**Description of the current state/issue**:

The default documentation points to the beta version (currently 3.0.0-beta)

**Link to the page**:

https://apisix.apache.org/docs/apisix/getting-started/

### Desired State

**Description of the change you are proposing**:

The default version should be the latest **production** version (currently 2.15).

** Reason**

Apache APISIX documentation users can roughly be separated into _production_ usage and R&D usage.

I assume that production usages:

1. Are more numerous
2. Are more critical
3. Are more important as they are using the product "for real"

Hence, we should focus on these usages more. Let's not waste our production users' time!

PS: I spent a non-trivial amount of time facing an issue with a plugin only because the JSON structure will change in 3.0.0-beta.

### Would you like to fix this issue?

No. Please assign another contributor

**Comment by SkyeYoung** [comment]
Good point, I'll try to fix it tomorrow and maybe add a beta label.

**Comment by guitu168** [comment]
Hi, no surprise, the production version of 3.0 will be released next week. The 3.0-beat version will be superseded.

please refer to: https://github.com/apache/apisix/pull/8179

I agree with nfrankel.

> Apache APISIX documentation users can roughly be separated into production usage and R&D usage.
