### ISSUE TITLE
[Docs]: 'docs' not found when use docker

### ISSUE THREAD

**Issue by hidaviddong** [iresty/iresty.github.io#1377]
### Current State

**Description of the current state/issue**:
'docs' folder not found in root directory
**Link to the page**:

**Screenshots (if relevant)**:
<img width="520" alt="Snipaste_2022-10-27_00-26-05" src="https://user-images.githubusercontent.com/73568310/198085282-0a871684-ddfa-4e6d-b0ea-38a8f1bc5d8c.png">

### Desired State

**Description of the change you are proposing**:
**In Dockerfile:**
- use `COPY ./doc /app/doc` to replace `COPY ./docs /app/docs`

**In docker-compose.yml**
- use `./doc:/app/doc` to replace `./docs:/app/docs`

<img width="500" alt="work" src="https://user-images.githubusercontent.com/73568310/198084836-4a965c44-fecd-4097-abdc-cf0ef369f1b6.png">

**Comment by SkyeYoung** [comment]
In fact, this Dockerfile has not been maintained since the original PR, and personally, I don't know the value and meaning of its existence. 🤔 

At the risk of asking, do you have any interest in helping to improve this part?

**Comment by SkyeYoung** [comment]
Maybe this can be closed by #1378 ? cc @juzhiyuan 

But in fact, this Dockerfile should still not work correctly. After all, the build scripts and project structure are now much different than before.

(I don't see the value of Dockerfile at this stage either.)
