### ISSUE TITLE
[Website]: Plugins page is incomplete

### ISSUE THREAD

**Issue by guitu168** [iresty/iresty.github.io#1379]
### Current State

**Description of the current state/issue**:
APISIX already supports 80+ plugins, but the PluginHub page only shows more than 40 plugins. 
**Link to the page**: https://apisix.apache.org/plugins/

**Screenshots (if relevant)**:

### Desired State

**Description of the change you are proposing**:

We could add the introduction information of other plugins to this page.

**Comment by SkyeYoung** [comment]
@uniqie are u interested?

**Comment by uniqie** [comment]
> @uniqie are u interested?
@SkyeYoung 🤣🤣🤣 at the weekend

**Comment by uniqie** [comment]
where can I find all the plugins supported? @SkyeYoung

**Comment by SkyeYoung** [comment]
@uniqie https://apisix.apache.org/docs/apisix/getting-started/
![image](https://user-images.githubusercontent.com/48400568/204943975-9890a2cf-900f-4681-a8d6-11c9a8d03d33.png)

Or https://github.com/apache/apisix/tree/master/apisix/plugins here you can.
