### ISSUE TITLE
[Site]: three pages were 404: plugins page, community channels page and open an issue page

### ISSUE THREAD

**Issue by zou8944** [iresty/iresty.github.io#1392]
### Current State

Three links in [get started page](https://apisix.apache.org/docs/apisix/getting-started/)
<img width="987" alt="image" src="https://user-images.githubusercontent.com/18495995/199737083-4ecf4d32-ce02-43af-8b04-b2a8892f06fb.png">

they are all 404

<img width="602" alt="image" src="https://user-images.githubusercontent.com/18495995/199737285-a9fa7e7d-2c2e-4cd3-9e63-9c6d705a0962.png">

The three links are:
- https://apisix.apache.org/docs/general/join/
- https://apisix.apache.org/plugins/
- https://apisix.apache.org/docs/general/submit-issue/

### Desired State

**Description of the change you are proposing**:
of course not 404

### Would you like to fix this issue?

Yes! Count me in

**Comment by guitu168** [comment]
@zou8944 hi, Thanks for the report. When I click on these three links, I get a `404`. And when I choose to open a new tab, it's accessible normally. We should fix the bug of not being accessible when clicked. cc @SkyeYoung
