### ISSUE TITLE
[Site][UI]:  i18n and style issues on /zh/blog/tags/* pages

### ISSUE THREAD

**Issue by SkyeYoung** [iresty/iresty.github.io#1400]
### Current State

**Description of the current state/issue**:

There are three problems with the current blog's Chinese `tags/*` pages:

1. `One post tagged with "xxx"`, `View All Tags` not translated
2. The number of posts is always `One post`
3. The style of `View All Tags` is black and difficult to be recognized by the human eye as a link (this problem also exists on the same page of the English blog, but of course, they use the same components, so it can be fixed at the same time)

**Link to the page**:

Example: https://apisix.apache.org/zh/blog/tags/community/

**Screenshots (if relevant)**:

<img width="879" alt="image" src="https://user-images.githubusercontent.com/48400568/200985707-c1343447-322f-4032-9b35-354864df645b.png">

### Desired State

**Description of the change you are proposing**:

1. translate `One post tagged with "xxx"`, `View All Tags`
2. fix "one post"
3. refactor `View All Tags` style

**Comment by uniqie** [comment]
I will fix it.

**Comment by uniqie** [comment]
I have found that translate command is different with 'docusaurus write-translations' in Docusaurus docs.
`"write-translations": "docusaurus-write-translations"`
It's confused for me to understand how did translation work execute in the past.

**Comment by SkyeYoung** [comment]
@uniqie pls see /apisix-website/blog/zh/i18n/zh/code.json, just as a example
