### ISSUE TITLE
The For More Information link on home page is 404[Site]: 

### ISSUE THREAD

**Issue by creedent** [iresty/iresty.github.io#1427]
### Current State

Clicking on the for more information link under the "shield against malicious" with security leads to a 404.  

Link
[](https://apisix.apache.org/docs/apisix/plugins/cors/)

### Desired State

Fix the link, or the endpoint.

### Would you like to fix this issue?

No. Please assign another contributor

**Comment by SkyeYoung** [comment]
@creedent We will fix this soon.
