### ISSUE TITLE
[Site]: Add new committers to the team page

### ISSUE THREAD

**Issue by yzeng25** [iresty/iresty.github.io#1437]
### Current State

**Description of the current state/issue**:
Seems like we got new committers recently, but the team page is not updated.
**Link to the page**:
https://apisix.apache.org/team/
**Screenshots (if relevant)**:
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/36651058/206350795-e0bc18d0-b3a6-4746-8dd8-50e9d1398538.png">

### Desired State

**Description of the change you are proposing**:
Each new committer should add their info to update the team page, or you can do it as whole. 

You can refer to previous pull requests like https://github.com/apache/apisix-website/pull/997 , https://github.com/apache/apisix-website/pull/998, and https://github.com/apache/apisix-website/pull/1435.

### Would you like to fix this issue?

No. Please assign another contributor

**Comment by SkyeYoung** [comment]
@AlinsRan @navendu-pottekkat 🚀

**Comment by SkyeYoung** [comment]
@guoqqqi pls help @navendu-pottekkat create a PR.

**Comment by guoqqqi** [comment]
> @guoqqqi pls help @navendu-pottekkat create a PR.

Done #1448
