### ISSUE TITLE
[Site]: Create/Improve "Contribute to Apache APISIX" page

### ISSUE THREAD

**Issue by Boburmirzo** [iresty/iresty.github.io#1440]
### Current State

**Description of the current state/issue**:

Create a new page called "How to contribute" under Contribute to APISIX section in the first list. Provide links to other pages in the table below.

**Link to the page**:

For Page, content ask @qu
**Screenshots (if relevant)**:

![image](https://user-images.githubusercontent.com/14247607/206920538-b1057aab-0d2f-4637-bf52-fbb922860f3c.png)

### Desired State

**Description of the change you are proposing**:

We need the well-described open-source contributor page for APISIX.

### Would you like to fix this issue?

No. Please assign another contributor

**Comment by guoqqqi** [comment]
I will solve this problem
