### ISSUE TITLE
[Site][UI]: the version of the dashboard on the Download page is not updated

### ISSUE THREAD

**Issue by whatbug** [iresty/iresty.github.io#1447]
### Issue description

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/32671621/206885271-2c194b31-620c-42f7-b35a-2cca7fa02460.png">

in apisix.apache.org latest version.

<img width="671" alt="image" src="https://user-images.githubusercontent.com/32671621/206885313-9d83efde-d596-4bc3-997b-6b792bd1cb34.png">
in github latest version.

### Expected behavior

???

### How to Reproduce

what is latest version ?

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by mscb402** [comment]
apisix-dashboard last version is 2.14 (published 7 day ago)
apisix-dashboard support APISIX version is 2.15

Therefore, there is indeed a problem with the display of apisix-dashboard version 2.13 on the official website. It should be that the document has not been updated

**Comment by SkyeYoung** [comment]
@whatbug In fact, it's the issue with the website, so I moved it here. 

@uniqie Could you help fix this?

**Comment by uniqie** [comment]
@SkyeYoung  🤩

**Comment by SkyeYoung** [comment]
@uniqie Hi, I think you can create a script in the https://github.com/apache/apisix-website/tree/master/scripts folder. Fetch and generate a JSON/JS file to maintain the repos' version info to help render the Download page simplify.

**Comment by SkyeYoung** [comment]
@uniqie Any update?

**Comment by uniqie** [comment]
At this weekend, i will deal with it.

**Comment by yzeng25** [comment]
@SkyeYoung @uniqie  It's 3.0.0 on the download page https://apisix.apache.org/downloads/ ;
![image](https://github.com/apache/apisix-website/assets/36651058/dd10feda-cd7e-4821-a9b6-ac49efa967f1)


and it is 3.0.1 on the github repo release page now https://github.com/apache/apisix-dashboard/releases.
![image](https://github.com/apache/apisix-website/assets/36651058/7389cc24-7dbc-42b7-902d-f0ad12afc955)

**Comment by SkyeYoung** [comment]
Looks like this have been solved.
