### ISSUE TITLE
[Site]: Overlapping of Architecture section on Hero section.

### ISSUE THREAD

**Issue by aspiringDev22** [iresty/iresty.github.io#1449]
### Current State

**Description of the current state/issue**:
The bottom of the hero section contains the "Downloads" and "View the docs" button which has been overlapped by the architecture page making the UI looks bad.

**Screenshots (if relevant)**:
![heropage](https://user-images.githubusercontent.com/102802211/207813620-68f73006-25b3-4d33-8640-a8b1ef45cfc5.png)

### Desired State

Increase the height of the Hero section so that the buttons would look better in the UI.

### Would you like to fix this issue?

Yes! Count me in

**Comment by Neilblaze** [comment]
@SkyeYoung was this issue resolved in a different PR? Cause on my end, everything seems fine (I've tried on both `16:9` & `21:9` aspect ratios). 

> **Update :** Screens with `23:15` aspect ratio will face this issue, although I believe, the ratio is quite rare & can be fixed with media queries.

I'd love to take a shot, if it's still up for grabs.

**Comment by SkyeYoung** [comment]
@Neilblaze This problem only occurs on some devices or windows with a special proportion. I think this problem can be closed. 🤔
