### ISSUE TITLE
[Docs]: Mismatching tags in "Why Is Apache APISIX the Best API Gateway?" blog

### ISSUE THREAD

**Issue by yzeng25** [iresty/iresty.github.io#1554]
### Current State

**Description of the current state/issue**:

Tags should be one or more of the following values

- Case Studies
- Ecosystem
- Authentication
- Plugins
- Community
- Vulnerabilities 

Yet the current tags for this page are not on the list.

**Link to the page**:

1. https://apisix.apache.org/blog/
2. https://apisix.apache.org/blog/2022/09/13/why-is-apache-apisix-the-best-api-gateway/
3. https://github.com/apache/apisix-website/pull/1320/files **line 15**

**Screenshots (if relevant)**:

![image](https://user-images.githubusercontent.com/36651058/231080406-112d1de4-bd7d-4fac-95b5-01dd0ea6df44.png)

### Desired State

**Description of the change you are proposing**:

- Find the best fit tag(s) from the current list and replace the current ones in `blog/en/blog/2022/09/13/why-is-apache-apisix-the-best-api-gateway.md`. Update the `zh-cn` file as well.
- (Optional) Update the tags list after discussion.

This this a pretty easy change, good first issue.

### Would you like to fix this issue?

No. Please assign another contributor

**Comment by 01vishu** [comment]
I am interested in contributing to your project and would like to request to be assigned to the project. I believe I have the necessary skills and expertise to make meaningful contributions to the project.

**Comment by yzeng25** [comment]
> I am interested in contributing to your project and would like to request to be assigned to the project. I believe I have the necessary skills and expertise to make meaningful contributions to the project.

Go for it, this shouldn't take you too long.
