### ISSUE TITLE
[Site]: Clicking on the doc version dropdown will bring the doc page to the first available doc

### ISSUE THREAD

**Issue by kayx23** [iresty/iresty.github.io#1583]
### Current State

Let's say we're on a plugin page. Now I want to switch doc version. The doc version dropdown shows up on hover, as expected. However if you accidentally (or out of habit) click on the dropdown, it brings the doc page to the first doc. 

For a demo, please see below gif: 

![20230509135256_rec_](https://user-images.githubusercontent.com/39619599/237006214-433c453c-2746-4147-80f6-5287790a873e.gif)

### Desired State

The "click" on the doc version dropdown should not have a different behaviour than the hover. 

### Would you like to fix this issue?

None

**Comment by yzeng25** [comment]
cc @SkyeYoung 👀

**Comment by ShantanuSutar** [comment]
Can I work on this issue?@kayx23

**Comment by yzeng25** [comment]
> Can I work on this issue?@kayx23

Assigned.
