### ISSUE TITLE
[Site]: Missed documentation about standalone mode

### ISSUE THREAD

**Issue by hamidrezakhosroabadi** [iresty/iresty.github.io#1613]
### Current State

**Description of the current state/issue**:
It seems there is no document for standalone mode since version 3.0 and according to this [change log](https://github.com/apache/apisix/blob/master/CHANGELOG.md) the standalone mode was not removed.
It causes to document conflicts and reduces document cohesion.

**Link to the page**:
https://apisix.apache.org/docs/apisix/3.3/stand-alone/

### Desired State

**Description of the change you are proposing**:
If standalone mode still exists in version 3.3, we can add the correspond documentation.

### Would you like to fix this issue?

Yes! Count me in

**Comment by yzeng25** [comment]
Hi @hamidrezakhosroabadi , thanks for bringing this issue up. However, the APISIX doc is in `apache/apisix` repo, see https://github.com/apache/apisix/tree/master/docs/en/latest. Can you create the issue there instead?

**Comment by hamidrezakhosroabadi** [comment]
> Hi @hamidrezakhosroabadi , thanks for bringing this issue up. However, the APISIX doc is in `apache/apisix` repo, see https://github.com/apache/apisix/tree/master/docs/en/latest. Can you create the issue there instead?

Sure!

**Comment by yzeng25** [comment]
@hamidrezakhosroabadi for your reference, I see the Standalone Mode changed from an individual doc to part of the doc in [Deployment modes](https://apisix.apache.org/docs/apisix/deployment-modes/#standalone).
