### ISSUE TITLE
[Site]: Missing Singapore event in the embeded Google Calendar

### ISSUE THREAD

**Issue by yzeng25** [iresty/iresty.github.io#1618]
### Current State

**Description of the current state/issue**:

Missing Singapore event in the embeded Google Calendar, would be nice to add it

**Link to the page**:

https://apisix.apache.org/docs/general/events/

**Screenshots (if relevant)**:

![apisix apache org_docs_general_events_](https://github.com/apache/apisix-website/assets/36651058/93ac960d-dac6-4669-8fe8-200f64c8664a)

### Desired State

**Description of the change you are proposing**:

Singapore event is in the embeded Google Calendar

### Would you like to fix this issue?

No. Please assign another contributor

**Comment by yzeng25** [comment]
Not sure how the calendar works, cc @navendu-pottekkat @guoqqqi .

**Comment by pottekkat** [comment]
Actually we have added the Singapore event to the calendar. The way it works now is that we have a Google Calendar and we add events to it.

But we are missing the Malaysia event.

<img width="907" alt="Screenshot 2023-06-16 at 5 36 50 PM" src="https://github.com/apache/apisix-website/assets/49474499/c0ab1033-9315-44d5-a7dc-4adb94e2c91f">

**Comment by pottekkat** [comment]
Added the Malaysia event as well.

**Comment by SkyeYoung** [comment]
Umm, so should we close this?

**Comment by yzeng25** [comment]
> Added the Malaysia event as well.

Thanks.
