### ISSUE TITLE
[Docs]: Typo found in Biweekly reports' posters

### ISSUE THREAD

**Issue by yzeng25** [iresty/iresty.github.io#1626]
### Current State

**Description of the current state/issue**:

**Link to the page**:
1. https://apisix.apache.org/blog/2023/06/21/weekly-report-en/ "communuty" --> "Community"
2. https://apisix.apache.org/blog/2023/06/08/weekly-report/ "communuty" --> "Community"
3. https://apisix.apache.org/blog/2023/05/24/weekly-report-0524/ "communuty" --> "Community"
4. https://apisix.apache.org/blog/2023/04/14/weekly-report-0414/ "community" --> "Community"

**Screenshots (if relevant)**:
Just click the links above and you will see typos in posters right away.

### Desired State

**Description of the change you are proposing**:

Fix typos. An example could be: https://apisix.apache.org/blog/2023/03/30/weekly-report-0330/

### Would you like to fix this issue?

No. Please assign another contributor

**Comment by lalitkumawat1m** [comment]
I want to work on this issue could you please assign me this issue ?

**Comment by yzeng25** [comment]
> I want to work on this issue could you please assign me this issue ?

Assigned.

**Comment by yzeng25** [comment]
@Qizeng-api7 can you also fix these typos and update the posters in EN and CN blogs?

**Comment by yzeng25** [comment]
Close via https://github.com/apache/apisix-website/pull/1650.
