### ISSUE TITLE
[Site]: Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [iresty/iresty.github.io#1677]
### Current State

**Description of the current state/issue**:

The Twitter logo has been updated recently and hasn't been updated on the site. I didn't find any issue related to this. hasn't

**Link to the page**:
https://apisix.apache.org/

**Screenshots (if relevant)**:

<img width="960" alt="Screenshot 2023-09-08 155001" src="https://github.com/apache/apisix-website/assets/91591901/fc39165d-5232-4053-bba0-475632671d4a">

@justinmclean 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

### Desired State

**Description of the change you are proposing**:

Twitter logo should be changed to X

### Would you like to fix this issue?

Yes! Count me in

**Comment by ShantanuSutar** [comment]
can I work on this issue?

**Comment by ShantanuSutar** [comment]
created a PR, please review @SkyeYoung @juzhiyuan @SylviaBABY  @yzeng25   - https://github.com/apache/apisix-website/pull/1678

**Comment by yzeng25** [comment]
#1683 should fix this.
