### ISSUE TITLE
[Docs]: error link

### ISSUE THREAD

**Issue by Erdan101** [iresty/iresty.github.io#1688]
### Current State

**Description of the current state/issue**:  link 404

**Link to the page**: https://apisix.apache.org/zh/docs/apisix/installation-guide/

**Screenshots (if relevant)**:

x
![image](https://github.com/apache/apisix-website/assets/76425125/e955fb75-1669-45da-9b1c-38f0345abbba)

### Desired State

**Description of the change you are proposing**:
Maybe change the link to https://apisix.apache.org/zh/docs/apisix/getting-started/README

### Would you like to fix this issue?

None

**Comment by umangutkarsh** [comment]
Could you please elaborate?

**Comment by yzeng25** [comment]
Fixed with 3.6 release.

Verification: https://apisix.apache.org/zh/docs/apisix/installation-guide/
