### ISSUE TITLE
[Docs]: A sentence in bi-weekly reports' picture is not showing up correctly

### ISSUE THREAD

**Issue by yzeng25** [iresty/iresty.github.io#1697]
### Current State

**Description of the current state/issue**:

Revision histories

1. Bi-weekly reports zh-cn and en-us 0828-0910 were created in #1684.
2. In bi-weekly reports zh-cn, plugin name was updated in #1687.

Discussion histories

1. Contributor claimed this issue is already fixed in https://github.com/apache/apisix-website/pull/1684#issuecomment-1735191402.
2. Pull request record shows contributor attempted to fix this issue in #1695 and #1696 , yet they were closed without reason.
3. When further asked for fixing plan under original pull request https://github.com/apache/apisix-website/pull/1684#issuecomment-1736604444, there is no response.

With revision histories for both files above, the claim is not accurate, and this problem is still out there.

![image](https://github.com/apache/apisix-website/assets/36651058/df5f08f8-8a1a-43e5-a7cf-36584b7f1122)

![image](https://github.com/apache/apisix-website/assets/36651058/4a689395-7904-4b78-bf37-10252c068a23)

**Link to the page**:

1. https://apisix.apache.org/blog/2023/09/13/biweekly-report/#contributor-statistics
4. https://apisix.apache.org/zh/blog/2023/09/13/biweekly-report/#%E8%B4%A1%E7%8C%AE%E8%80%85%E7%BB%9F%E8%AE%A1

**Screenshots (if relevant)**:

![image](https://github.com/apache/apisix-website/assets/36651058/5a467529-4486-4098-bbef-d5e672d0a059)

### Desired State

**Description of the change you are proposing**:

1. Upload a new picture and generate a new link i.e. `https://static.apiseven.com/uploads/2023/09/26/afJdz8VA_Group%204.png` (from #1695 and #1696).
2. Create a pull request, in which you will replace the old link with the new link in both files.

Alternatively, skipping 1&2 above, and reopening #1695 and #1696 is also an option.

I think the description and solution are clear enough for you to follow and fix the issue @Yilialinn @JYan00 .

Attached is the modified and ready-to-use image from from #1695 and #1696 
![image](https://github.com/apache/apisix-website/assets/36651058/ed8f2b2c-f7d7-417d-a811-54825d24b251)

### Would you like to fix this issue?

No. Please assign another contributor

**Comment by saltism** [comment]
Hi,

I checked https://github.com/apache/apisix-website/pull/1695 and https://github.com/apache/apisix-website/pull/1696, images are shown correctly. But the official websites https://apisix.apache.org/blog/2023/09/13/biweekly-report/ and https://apisix.apache.org/zh/blog/2023/09/13/biweekly-report/ still remain the wrong ones.

I mistakenly closed the pull request because I thought the fixing task was done, sorry for the trouble that I caused. Now you can merge it and the correct ones will be displayed on the website.

**Comment by yzeng25** [comment]
> Hi,
> 
> I checked #1695 and #1696, images are shown correctly. But the official websites https://apisix.apache.org/blog/2023/09/13/biweekly-report/ and https://apisix.apache.org/zh/blog/2023/09/13/biweekly-report/ still remain the wrong ones.
> 
> I mistakenly closed the pull request because I thought the fixing task was done, sorry for the trouble that I caused. Now you can merge it and the correct ones will be displayed on the website.

The task is done when the following process is done,

Create pull request -> Review/Revise based on review -> 2 or more approvals ->Merge pull request -> Deploy changes on the website.

Also note how I modify the descriptions in both of your pull requests, it helps other reviewers understand what is going on and ease the review process.

It is deploying now, the process takes about 30 min.

![image](https://github.com/apache/apisix-website/assets/36651058/8c848ca1-d7bf-4089-b413-05532e439709)

When successfully deployed, the first two line descriptions are different.

![image](https://github.com/apache/apisix-website/assets/36651058/258c3673-6797-41ae-ab34-8099597a8ac3)

To ensure your changes are effective, visit the online links after successfully deployed.
