### ISSUE TITLE
[Site]: Delay in UI responsiveness

### ISSUE THREAD

**Issue by umangutkarsh** [iresty/iresty.github.io#1698]
### Current State

I am currently experiencing some delay in the UI responsiveness of the website, when for example any options from navbar is opened.

**Link to the page**: https://apisix.apache.org/docs/apisix/getting-started/README/

**Screenshots (if relevant)**: 
<img width="943" alt="apache" src="https://github.com/apache/apisix-website/assets/95426993/b3fa587d-9f96-49e7-9903-73f8ce658601">

### Desired State

**Description of the change you are proposing**:

The UI delay should be fixed

### Would you like to fix this issue?

None

**Comment by Keshav-0907** [comment]
Can i work on this issue ??

**Comment by SkyeYoung** [comment]
@Keshav-0907 Thx!

**Comment by Keshav-0907** [comment]
Working fine now

```I have checked for different screen resolutions also, and everything seems to be working fine. ```

<img width="1440" alt="Screenshot 2023-11-02 at 3 16 09 AM" src="https://github.com/apache/apisix-website/assets/91189139/637c795c-d9a9-4d5f-9745-8f5ac5f7193b">

**Comment by SkyeYoung** [comment]
Looks like have been fixed.
