### ISSUE TITLE
[Site] Search Icon overlays Dark Mode toggle in mobile view

### ISSUE THREAD

**Issue by Keshav-0907** [iresty/iresty.github.io#1719]
### Current State

**Description of the current state/issue**:

The Search icon overlays, the Dark Mode toggle button in Mobile View in the navbar.

**Link to the page**: https://apisix.apache.org/docs/apisix/getting-started/README/

**Screenshots (if relevant)**:
<img width="351" alt="Screenshot 2023-10-31 at 4 29 59 PM" src="https://github.com/apache/apisix-website/assets/91189139/4c5540d3-7bd5-4166-b54f-79771f571441">

### Desired State

**Description of the change you are proposing**:

Adjusting both the objects, so that they don't overlay each other

### Would you like to fix this issue?

Yes! Count me in

**Comment by Keshav-0907** [comment]
@yzeng25 @jiangfucheng @SylviaBABY

**Comment by SylviaBABY** [comment]
@Keshav-0907 thanks for your contribution!

**Comment by Keshav-0907** [comment]
@SylviaBABY @yzeng25 

While setting up the project locally got this error repeatedly. Can you please help me find a solution for this ??

![image](https://github.com/apache/apisix-website/assets/91189139/3c125949-e57e-4010-a021-0a702daa9e4c)

**Comment by yzeng25** [comment]
> @SylviaBABY @yzeng25
> 
> While setting up the project locally got this error repeatedly. Can you please help me find a solution for this ??
> 
> ![image](https://user-images.githubusercontent.com/91189139/279809249-3c125949-e57e-4010-a021-0a702daa9e4c.png)


cc @SkyeYoung

**Comment by SkyeYoung** [comment]
@Keshav-0907 Hi, Sorry to reply to you so late (I've been getting a lot of emails lately, so I'm missing some).  

What system are you using? Since I only develop on Linux, there may be some compatibility issues.

**Comment by Keshav-0907** [comment]
No worries @SkyeYoung 

I am using a M1 Chip -  Macbook

**Comment by SkyeYoung** [comment]
Okay, I'll go find a Macbook and try it out a little later after I post this comment

**Comment by Keshav-0907** [comment]
Okay, Thank you :)

**Comment by SkyeYoung** [comment]
Sorry, last weekend I had some other things to do at the last minute. I will try today.

**Comment by SkyeYoung** [comment]
@Keshav-0907 Hi, it looks very strange. I didn't find the issue described in your image, but instead encountered some other problems (which I have addressed in [this PR](https://github.com/apache/apisix-website/pull/1727)).

Could you please try manually accessing the path as described in the command?

e.g.:

```bash
# replace the apisix-website/scripts/generate-event-poster-card.sh
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")/..

test -e ${SCRIPTPATH}/config/event-poster-card.json 
test -e ${SCRIPTPATH}/website/src/theme/Footer/
```

**Comment by siyaramsujan** [comment]
@SkyeYoung Hi, it looks like the issue with the search icon overlapping the theme toggle button is only happening when initially opening the page on desktop and switching to mobile view. However, the problem is resolved when you refresh the page after the switch or when initially opening it on mobile devices. When switching to the mobile view, the toggle button is moving to the collapsed side menu, but it's not removed or hidden from the right-side nav, as shown in the gif below. 
![i-1719](https://github.com/apache/apisix-website/assets/91601717/3163da21-780e-48e5-9297-87ff751f83c9)

**Comment by siyaramsujan** [comment]
Hi, It was only a problem in the docs route and I've fixed the issue locally and would love to contribute. Could you please assign this task to me for confirmation? Thank you! 😊
