### ISSUE TITLE
[Site]: Update Blog summary pages

### ISSUE THREAD

**Issue by yzeng25** [iresty/iresty.github.io#1751]
### Current State

**Description of the current state/issue**:

The "Featured" and "Editors' Picks" sections on both summary pages only cover from late 2022 to Jan - June/Jul of 2023.

Should take a look at the stats of Jul/Aug - Dec 2023 contents and decide what to update.

**Link to the page**:
- EN-US https://apisix.apache.org/blog/
- ZH-CN https://apisix.apache.org/zh/blog/

**Screenshots (if relevant)**:
EN-US
![image](https://github.com/apache/apisix-website/assets/36651058/0b5ec466-29eb-4704-ad19-3987778e0bba)

ZH-CN
![image](https://github.com/apache/apisix-website/assets/36651058/98706095-6a39-4e2b-9037-4facc7bf1629)

### Desired State

**Description of the change you are proposing**:

Some or all contents are updated based on most viewed or other sort of content strategy. The current ones seems to be out of date.

### Would you like to fix this issue?

No. Please assign another contributor

**Comment by SkyeYoung** [comment]
@guoqqqi pls help with this.

**Comment by guoqqqi** [comment]
Hi @Yilialinn Can you help resolve this issue?

**Comment by yzeng25** [comment]
Close via https://github.com/apache/apisix-website/pull/1786.

**Comment by Yilialinn** [comment]
> Hi @Yilialinn Can you help resolve this issue?

Sorry for my late reply.

**Comment by Yilialinn** [comment]
> ### Current State
> **Description of the current state/issue**:
> 
> The "Featured" and "Editors' Picks" sections on both summary pages only cover from late 2022 to Jan - June/Jul of 2023.
> 
> Should take a look at the stats of Jul/Aug - Dec 2023 contents and decide what to update.
> 
> **Link to the page**:
> 
> * EN-US https://apisix.apache.org/blog/
> * ZH-CN https://apisix.apache.org/zh/blog/
> 
> **Screenshots (if relevant)**: EN-US ![image](https://private-user-images.githubusercontent.com/36651058/293636440-0b5ec466-29eb-4704-ad19-3987778e0bba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzA2NTQsIm5iZiI6MTcxMjEzMDM1NCwicGF0aCI6Ii8zNjY1MTA1OC8yOTM2MzY0NDAtMGI1ZWM0NjYtMjllYi00NzA0LWFkMTktMzk4Nzc3OGUwYmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA3NDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMTEyM2UwOTJjNWNlM2Q4NTEzNDBjOGYxNzUxMjczNmUzODVmMmE3OTg2OTQwYjYzYTY1ZDIyMzIzOGMyNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pMlFff7ljcigbakmdWrR_Zf75Is8sJKZMzDdtG4yTf0)
> 
> ZH-CN ![image](https://private-user-images.githubusercontent.com/36651058/293636509-98706095-6a39-4e2b-9037-4facc7bf1629.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzA2NTQsIm5iZiI6MTcxMjEzMDM1NCwicGF0aCI6Ii8zNjY1MTA1OC8yOTM2MzY1MDktOTg3MDYwOTUtNmEzOS00ZTJiLTkwMzctNGZhY2M3YmYxNjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA3NDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkNDYyZGMyMDZlZjdhMjE1MjE4MDJlNjhhMmVmNTdiY2JiMzNiYzk1NmYzOGIwNzU0ZDFmMzZiMmIzMjcyMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uKAgGjBARFRubhxx7mANzM94hFB2_I_dIqiFbUYkt_Q)
> 
> ### Desired State
> **Description of the change you are proposing**:
> 
> Some or all contents are updated based on most viewed or other sort of content strategy. The current ones seems to be out of date.
> 
> ### Would you like to fix this issue?
> No. Please assign another contributor

I will update the editors' picks every month
