### ISSUE TITLE
[Site]: getting-started 404 page not found

### ISSUE THREAD

**Issue by karnzx** [iresty/iresty.github.io#1768]
### Current State

**Description of the current state/issue**:
- open https://apache-apisix.netlify.app/
- click "Docs" dropdown on navbar and select "Apache APISIX"

**Link to the page**:
https://apache-apisix.netlify.app/docs/apisix/getting-started/
**Screenshots (if relevant)**:
![image](https://github.com/apache/apisix-website/assets/26167071/7d23f288-0773-4b17-93de-16057f2dfacd)

### Desired State

**Description of the change you are proposing**:
want able to access the docs

### Would you like to fix this issue?

Yes! Count me in

**Comment by yzeng25** [comment]
@karnzx  try https://apisix.apache.org/
