### ISSUE TITLE
docs: editing url valid 

### ISSUE THREAD

**Issue by sunheyi6** [iresty/iresty.github.io#1783]
### Current State

in this [url](https://apisix.apache.org/edit/) and  this [url](https://apisix.apache.org/zh/edit/);
There is no response when clicking this button and it will not jump to other pages.
![image](https://github.com/apache/apisix/assets/50973219/c7fd2b77-7403-4ed4-9c32-2716dfc0f252)

### Desired State

Automatically jump to the warehouse where modifications can be submitted

**Comment by yzeng25** [comment]
cc @SkyeYoung

**Comment by SkyeYoung** [comment]
Hi, please provide the origin urls.

This page should appear after clicking the edit button, e.g.:

<img width="730" alt="image" src="https://github.com/apache/apisix-website/assets/48400568/fc29e0e0-0ee8-4ad4-b330-ed6f192715cb">

<br>
<br>


After jump, the url will be:

```
https://apisix.apache.org/edit/#https://github.com/apache/apisix/edit/release/3.9/docs/en/latest/getting-started/README.md
```

I think maybe we can jump to github repo index page, if no hash param 🤔

**Comment by siyaramsujan** [comment]
Hi, could I be assigned to this task? Thanks!
