### ISSUE TITLE
[Site]: Wrong images in Monthly Report (May 01 - May 31) blog

### ISSUE THREAD

**Issue by yzeng25** [iresty/iresty.github.io#1799]
### Current State

**Description of the current state/issue**:

1. Date on the upper right corner should be 05.01-05.31 to align with the texts.
2. The last sentence is blurred and does not show up completely. It should be "Thanks for contributing to ..."

**Link to the page**:
Related PR and codes:
- https://github.com/apache/apisix-website/pull/1798
- https://github.com/apache/apisix-website/pull/1798/files#diff-f2e8eeeee260baba09485d73f4094621f3728a8e0bf7faa91ae886f49b67cb29R19
- https://github.com/apache/apisix-website/pull/1798/files#diff-2425a1af1f5ae453fc9eb494d5c95cb94bc8f09797aeb2f726d4d64b53b880d4R18

EN: https://apisix.apache.org/blog/2024/05/31/monthly-report/
ZH: https://apisix.apache.org/zh/blog/2024/05/31/monthly-report/

**Screenshots (if relevant)**:
![image](https://github.com/apache/apisix-website/assets/36651058/1cbf78f6-b257-4bc9-bb29-628eeecaf9ce)

### Desired State

**Description of the change you are proposing**:

Change date on the upper right corner should be 05.01-05.31

Update the last sentence such that it shows up clear and complete.

### Would you like to fix this issue?

None

**Comment by yzeng25** [comment]
@bzp2010 @kayx23 @SkyeYoung @moonming @membphis

**Comment by Yilialinn** [comment]
> @bzp2010 @kayx23 @SkyeYoung @moonming @membphis

The images will be fixed in https://github.com/apache/apisix-website/pull/1800

**Comment by kayx23** [comment]
fixed in #1800
