### ISSUE TITLE
[Site]: Remove kapa.ai bot from website due to ASF Policy

### ISSUE THREAD

**Issue by justinmclean** [iresty/iresty.github.io#1808]
### Current State

Kapa.ai is not allowed to use used as we don't have an privacy agreement with them and they potentially store users' queries

### Desired State

Remove use of Kapa.ai

### Would you like to fix this issue?

No. Please assign another contributor

**Comment by yzeng25** [comment]
Kapa.ai was added on Jan 11th by @zll600 and approved by @monkeyDluffy6017 and @moonming  in https://github.com/apache/apisix-website/pull/1756

Modifications were made in https://github.com/apache/apisix-website/pull/1757 on Jan 11th, https://github.com/apache/apisix-website/pull/1773 on Feb 21st, and https://github.com/apache/apisix-website/pull/1774 on Feb 22nd; which were approved by @monkeyDluffy6017 , @moonming , @SkyeYoung , and @LiteSun .

Apache SkyWalking website removed Kapa.ai on July 17th by: https://github.com/apache/skywalking-website/pull/727

Apache DolphinScheduler website removed Kapa.ai on June 18th by: https://github.com/apache/dolphinscheduler-website/pull/962

Also see [ASF Data Privacy](https://privacy.apache.org/policies/website-policy.html).

**Comment by moonming** [comment]
@yzeng25 welcome PR to remove it.

**Comment by yzeng25** [comment]
> @yzeng25 welcome PR to remove it.

I don't have the bandwidth to do it. Please find someone else to handle it.
