### ISSUE TITLE
[Site]: Duplicates of a blog in the blog summary page

### ISSUE THREAD

**Issue by yzeng25** [iresty/iresty.github.io#1811]
### Current State

**Description of the current state/issue**:

Duplicates of the blog 'Advanced URL rewriting with Apache APISIX' appears in the blog summary page

**Link to the page**:

https://apisix.apache.org/blog/

**Screenshots (if relevant)**:

![image](https://github.com/user-attachments/assets/05b79a56-2e4c-4b8f-aa8e-11f72af9e057)

### Desired State

**Description of the change you are proposing**:
The blog 'Advanced URL rewriting with Apache APISIX' was added in #1806 .

Anonther blog was added in #1810 with the same title. Per checked file name and canonical link in the file, the title should be 'Differentiating rate limits in Apache APISIX' instead.

Change [line 2](https://github.com/apache/apisix-website/blob/master/blog/en/blog/2024/07/25/different-rate-limits-apisix.md?plain=1#L2) in the [file](blog/en/blog/2024/07/25/different-rate-limits-apisix.md) to `title: Differentiating rate limits in Apache APISIX` should fix this easily.

### Would you like to fix this issue?

No. Please assign another contributor

**Comment by Souvik-Cyclic** [comment]
@pottekkat close this issue, as #1814 fixed this.

**Comment by yzeng25** [comment]
Closed via #1814
