### ISSUE TITLE
discuss: a new structure of Apache APISIX website

### ISSUE THREAD

**Issue by Serendipity96** [iresty/iresty.github.io#607]
**Actual Behaviour**

I found that Apache APISIX website is not very convenient, I often can't find the content that I want. But after browsing many times, I found Apache APISIX website is very informative.

I've also followed  Apache APISIX other media and found a lot of really great content that isn't posted on the website.

I have listed some of the problems on the website：

- Apache APISIX website modules are not clear, e.g.
    * Homepage: The introduction of Apache APISIX on the homepage is not complete. The full features are on the Github [readme](https://github.com/apache/apisix).     
    * Events: Events module does not have a dedicated tab on the nav. There are only 4 information introductions are displayed on the homepage, which is hard to be noticed. The content on the events page is not categorized.
    * Blog: Blog show too little information, and the style is simple.
    * Docs: The document structure is deep and hard to find.
    * Language: There are two languages on the website, but the English and Chinese contents are mixed together.
    * There is no content under the existing modules, such as news 

-  Lack of linking channels to contributors
    * Except for good first issues ，for potential and new contributors (like me), I don't know what can I contribute.  
    * Contact information is hidden too deep, it is in the second level under the tab. Or I change to Apache APISIX Github to find contact information.

- Apache APISIX has a lot of learning materials and information, but the website is not the most comprehensive.

I think a useful contributor site is the first step to attract contributors. What do you think？

**Expected Behaviour**

Based on the above problems, I came up with a solution to make Apache APISIX website better and easier to find learning materials, and I hope more and more people will participate in contributing to Apache APISIX. I have drawn a prototype of the website, please take a look.

**This is homepage. Show Apache APISIX features, events, and ways to join the community on the homepage.**

![image](https://user-images.githubusercontent.com/23514812/133559306-773ba086-cc73-404d-ae53-433cfb820265.png)

**This is learning page. There are a lot of Apache APISIX learning materials, e.g. blogs, videos, user cases ……**

![image](https://user-images.githubusercontent.com/23514812/133559328-c5bfa458-f51f-466f-a862-dcdcc64325eb.png)

![image](https://user-images.githubusercontent.com/23514812/133559351-56bb478d-d0ac-4ec6-ac07-4ffa9d9446dd.png)

**This is Event page. About the event page, I posted an [issue](https://github.com/apache/apisix-website/issues/473) a month ago.**

![image](https://user-images.githubusercontent.com/23514812/133559370-cb5185d9-1b61-4a7a-9cb1-a310228a0655.png)

**This is Contribute page. Show a lot of ways to contribute content, like translating blog, posting videos, recieving good first issues.**

![image](https://user-images.githubusercontent.com/23514812/133559499-9de9dc82-e6ea-4b31-bac6-db572843ad66.png)

**Comment by 1502shivam-singh** [comment]
Hi @Serendipity96,
Appreciate your work on highlighting the problems. We are aware of most (if not all) issues that you have highlighted here and are working in a stepwise manner to solve this bigger problem by solving the smaller sub problems.

As of completed checkpoints, I personally have worked out the homepage redesign and code and the plugin hub page design (wireframe only). The new homepage is in discussion to be merged, check it out at [apisix-redesign](https://apisix-re.netlify.app/) this solves all the issues that you mentioned for the home page while being asthetically pleasing.

Currently we are working on improving the blog section of apisix-website, making it along the lines of the design of the homepage for uniformity throughout. 

We will try our best to accomodate all your suggestions/recommendations along the way 😊.

**Comment by Serendipity96** [comment]
hi @1502shivam-singh,
Wow, the new version of the Apache APISIX homepage is so cool. 
The introduction of Apache APISIX has become rich and the homepage style is fashion. 
I know my question is too much and there are still a lot of details to discuss.
You mentioned that the blog page is being revamped, can you introduce more information? Can I join the discussion?

**Comment by 1502shivam-singh** [comment]
> I know my question is too much and there are still a lot of details to discuss.

Not really, actually you are asking and raising the right issues that weren't raised way earlier. Happy that more people are expressing these problems and raising issues :)    

> You mentioned that the blog page is being revamped, can you introduce more information? Can I join the discussion?

Sure ! You can start from #490 to track the discussion and follow along.

**Comment by Serendipity96** [comment]
@1502shivam-singh , thank you very much for your encouragement. It's really a pleasure to discuss in the community. I believe Apache APISIX website will get better and better.

I have read all these [discussions](https://github.com/apache/apisix-website/issues/490), you have done careful research.  I think I can add some new article tags and sort them by new tags.

**Comment by Serendipity96** [comment]
I have designed a plan for the blog issue raised above. 
First, let me briefly describe my plan: I have divided APISIX related material into two categories, one is blog and the other is video. Blogs and videos will be added tags, so that everyone can easily find the information according to his or her needs.

![image](https://user-images.githubusercontent.com/23514812/136888944-f16584c9-cb2f-4f42-8dc4-a0389e695a70.png)

APISIX related materials are divided into two categories, one is articles and the other is videos.
**description**:
Click on the navigation bar `blog` to enter the page. By default, select [Articles] category.
Click the [Article] [Video] tab to switch to the corresponding page.

<div data-zone-id="0" data-line-index="0" style="white-space: pre;"><h2 class="heading-h2">1.1 Article List Page
</h2></div><div data-zone-id="0" data-line-index="1" style="white-space: pre;"><h3 class="heading-h3">Classification
</h3></div><div data-zone-id="0" data-line-index="2" style="white-space: pre;">Under the article tab, perform secondary classification. The following are all classifications:
</div><div data-zone-id="0" data-line-index="3" style="white-space: pre;">

Classification | Description
-- | --
Latest | The time sequence is reversed, the latest published articles are placed at the top, and all articles are listed.
Tech | Technical solution, implementation principle, source code interpretation, architecture design type articles
User Case | User case
Best Practices | Collaboration with other communities/technologies to run APISIX on other platforms, eg: Rancher × APISIX,
Weekly Report | Community weekly report
Events | Event previews migrated from the Events page
Release | APISIX release, feature articles, and release logs
Easy | Easy article
Medium | Medium article
Hard | Hard Articles

</div>


<div data-zone-id="0" data-line-index="0" style="white-space: pre;"><h2>
</h2></div><div data-zone-id="0" data-line-index="1" style="white-space: pre;"><h3 class="heading-h3">Article Introduction
</h3></div><div data-zone-id="0" data-line-index="2" style="white-space: pre;">
</div><div data-zone-id="0" data-line-index="3" style="white-space: pre;">
</div>

The article introduction includes:
- Title
- Author name
- Article introduction
- tags
- Release time, reading time

To sum up, the content is not much different from the following screenshots, mainly add the cover picture.

![image](https://user-images.githubusercontent.com/23514812/136889427-d3cf5eae-8184-4c7d-983d-6df79f76aa7e.png)

The purpose of adding a cover image:
- Display corporate case logo
- Improve the aesthetics of the article list page

<div data-zone-id="0" data-line-index="0" style="white-space: pre;"><h2>
</h2></div><div data-zone-id="0" data-line-index="1" style="white-space: pre;"><h3 class="heading-h3">Pagination
</h3></div><div data-zone-id="0" data-line-index="2" style="white-space: pre;">
</div><div data-zone-id="0" data-line-index="3" style="white-space: pre;">
</div>

Add a pagination button at the bottom of the article list.

![image](https://user-images.githubusercontent.com/23514812/136889499-fc32121d-20e9-41cc-8efb-15e9fc29015c.png)

<div data-zone-id="0" data-line-index="0" style="white-space: pre;"><h2>
</h2></div><div data-zone-id="0" data-line-index="1" style="white-space: pre;"><h3 class="heading-h3">Label
</h3></div><div data-zone-id="0" data-line-index="2" style="white-space: pre;">
</div><div data-zone-id="0" data-line-index="3" style="white-space: pre;">
</div>
Remove recent posts and change to tags collection Article tag collection.

**description**:

Click on a tag, the page will select the "latest" category by default, and display the articles under the tag, and the paging button will be displayed at the bottom.

Tag only supports selecting one at a time.

**Example 1**: In the user case, select Ingress and take the intersection of the two.

![image](https://user-images.githubusercontent.com/23514812/136889689-8cddd5dc-8129-4ddb-8664-1d4eaf2399c3.png)

**Example 2**: Under Weekly Report, select Ingress, no releated content, so show the content of the article classification first, that is, the Weekly Report list.

![image](https://user-images.githubusercontent.com/23514812/136889865-e822ae5c-f1ca-4904-84ff-f4973b6660a6.png)



<div data-zone-id="0" data-line-index="0" style="white-space: pre;"><h2 class="heading-h2">1.2 Article Details Page
</h2></div><div data-zone-id="0" data-line-index="1" style="white-space: pre;"><h3 class="heading-h3">
</h3></div><div data-zone-id="0" data-line-index="2" style="white-space: pre;">
</div><div data-zone-id="0" data-line-index="3" style="white-space: pre;">


No modified features.
- Keep the previous and subsequent article recommendation buttons at the bottom.
- Keep the bottom Tags to click and jump to the corresponding category.
- Still keep the latest release on the left as a recommendation.

![image](https://user-images.githubusercontent.com/23514812/136890100-9415cde9-e1c9-4e57-9cea-c51121a4292f.png)

<div data-zone-id="0" data-line-index="0" style="white-space: pre;"><h2 class="heading-h2">2.1 Video List Page
</h2></div><div data-zone-id="0" data-line-index="1" style="white-space: pre;">Existing videos on youtube site, on twitter, ApacheCon video on API7 website.
</div><div data-zone-id="0" data-line-index="2" style="white-space: pre;"><h3 class="heading-h3">Classification
</h3></div><div data-zone-id="0" data-line-index="3" style="white-space: pre;">
</div>

Classification | Description
-- | --
Latest | The time sequence is reversed, the latest published articles are placed at the top, and all articles are listed.
Tech | Technical solution, implementation principle, source code interpretation, architecture design type videos
User Case | user case
Best Practices | Collaboration with other communities/technologies to run APISIX on other platforms, eg: Rancher × APISIX,
Events | Like ApacheCon
Release | APISIX release, function introduction videos
Easy |  Easy videos
Medium | Medium videos
Hard | Hard videos

![image](https://user-images.githubusercontent.com/23514812/136890454-61b73699-35ee-438f-abbf-e917c1f0c084.png)


<div data-zone-id="0" data-line-index="0" style="white-space: pre;"><h2>
</h2></div><div data-zone-id="0" data-line-index="1" style="white-space: pre;"><h3 class="heading-h3">Video Introduction
</h3></div><div data-zone-id="0" data-line-index="2" style="white-space: pre;">
</div><div data-zone-id="0" data-line-index="3" style="white-space: pre;">
</div>

- Video Cover
- Video duration
- Title
- Release time
Example:

![image](https://user-images.githubusercontent.com/23514812/136890539-eb75131c-74ba-4d42-a68c-448198e3b638.png)


<div data-zone-id="0" data-line-index="0" style="white-space: pre;"><h2>
</h2></div><div data-zone-id="0" data-line-index="1" style="white-space: pre;"><h3 class="heading-h3">Pagination
</h3></div><div data-zone-id="0" data-line-index="2" style="white-space: pre;">
</div><div data-zone-id="0" data-line-index="3" style="white-space: pre;">
</div>
Pagination
Add a pagination button at the bottom of the video list.

![image](https://user-images.githubusercontent.com/23514812/136890577-4aeaabbe-dbb6-4e84-8616-64c1134aa05a.png)

<div data-zone-id="0" data-line-index="0" style="white-space: pre;"><h2 class="heading-h2">2.2 Video Details Page
</h2></div><div data-zone-id="0" data-line-index="1" style="white-space: pre;">
</div><div data-zone-id="0" data-line-index="2" style="white-space: pre;"><h3 class="heading-h3">Classification
</h3></div><div data-zone-id="0" data-line-index="3" style="white-space: pre;">
</div>

- Video Title
- Video release date
- Video tag

![image](https://user-images.githubusercontent.com/23514812/136890690-9a94f15c-ea0f-4ace-b3b7-f869f55405a0.png)


<div data-zone-id="0" data-line-index="0" style="white-space: pre;"><h2 class="heading-h2">3.1 Search 
</h2></div><div data-zone-id="0" data-line-index="1" style="white-space: pre;">
</div><div data-zone-id="0" data-line-index="2" style="white-space: pre;"><h3 class="heading-h3">
</h3></div><div data-zone-id="0" data-line-index="3" style="white-space: pre;">
</div>


![image](https://user-images.githubusercontent.com/23514812/136890802-22e1a09b-fb62-4cfe-8070-43c067f52715.png)

![image](https://user-images.githubusercontent.com/23514812/136890789-bfb12fbf-a692-4bad-9aa5-184fc6ff3b4b.png)

After adding the video, can the search bar find the video and support jumping?

@juzhiyuan @1502shivam-singh @yzeng25 What do you think? Looking forward to your feedback, thanks.

**Comment by 1502shivam-singh** [comment]
Woh, a really detailed document. Maybe store it all as a markdown file, so that it doesn't get lost in the comments and can be referred later.

One question though, what exactly would be in the videos tab ? Can we adjust videos in related articles, like attaching the ApacheCon video in the ApacheCon articles for instance. What I am trying to emphasize here, is maybe let the majority of video content on respective platform (YouTube, Vimeo, etc.) to provide the brand of Apache APISIX some traction in that area. 

Some few videos on main website and specific ones in articles, acting as a funnel to the APISIX's Youtube channel (or channel on another platform)    
What you all feel on this ?

**Comment by Serendipity96** [comment]
Yeah, store the content as a markdown file is a good suggestion. Where should the markdown be placed? Do you have a good suggestion?

I want to make a collection of Apache APISIX related videos, so that everyone can see the most complete Apache APISIX material on the website, instead of finding it elsewhere. Some of the videos do not have corresponding articles, but they are good sources for learning and understanding Apache APISIX.

**Comment by 1502shivam-singh** [comment]
> Yeah, store the content as a markdown file is a good suggestion. Where should the markdown be placed? Do you have a good suggestion?

Not really sure on this, maybe others can chime in and suggest. For now, atleast keep one with you. I usually like [trello](https://trello.com/en) boards or similar to track plans like this, like a board with checkpoints and links with reference to plans. Really, depends on your workflow.

> I want to make a collection of Apache APISIX related videos, so that everyone can see the most complete Apache APISIX material on the website, instead of finding it elsewhere. Some of the videos do not have corresponding articles, but they are good sources for learning and understanding Apache APISIX.

Okay, understood. Like a video collection at one place.

**Comment by Serendipity96** [comment]
>Not really sure on this, maybe others can chime in and suggest. For now, atleast keep one with you. I usually like trello boards or similar to track plans like this, like a board with checkpoints and links with reference to plans. Really, depends on your workflow.

Thanks, let me see.

**Comment by Serendipity96** [comment]
Hi @juzhiyuan , How is it going？

Do you need some help? I‘m not familiar with React, but I've coded some projects using Vue. Maybe I can finish some features.

If you assign some features to me, I think we should discuss the technical solutions together.

If I finish the function, how can I test using related backend data?

**Comment by juzhiyuan** [comment]
confirmed with @Serendipity96, she will continue to resolve those issues when she has time.

**Comment by Serendipity96** [comment]
hi @juzhiyuan @1502shivam-singh, I finished the development of the first part of Contribute Page. please take a look [here](
https://github.com/apache/apisix-website/pull/758).

**Comment by SkyeYoung** [comment]
@juzhiyuan @Serendipity96 @guoqqqi 

It seems like there's a lot that's been done here, and a lot that hasn't been done or needs to be done. But this issue has been around for so long that many of the descriptions no longer fit the current scenario, so maybe we can close this issue and discuss the site's structure in a new issue.
