### ISSUE TITLE
About the i18n of blogs

### ISSUE THREAD

**Issue by Baoyuantop** [iresty/iresty.github.io#623]
**Actual Behaviour**

Currently, our blogs are mixed in English and Chinese. All blogs are displayed whether in English or Chinese. This often brings confusion and inconvenience to users of different languages.

**Expected Behaviour**

When the current environment is in English, only English blogs are displayed, and in the Chinese environment, only Chinese blogs are displayed.

After analysis, we can use the [`draft`](https://docusaurus.io/zh-CN/docs/api/plugins/@docusaurus/plugin-content-blog#markdown-frontmatter) property of the markdown file to solve, It means that the current document is still in draft and will not be displayed in the blog.

So because we default to the English environment, add the `draft` property to all Chinese blogs in the `website/blog` directory.

After that, copy all the blog files to the `website/i18n/zh/docusaurus-plugin-content-blog` directory, and then add the `draft` property to all English blogs.

**Note**: draft will still be displayed in development mode, but after build, it works ~

What do you think？

**Comment by liuxiran** [comment]
Hi @Baoyuantop , there is a [pr](https://github.com/apache/apisix-website/pull/550) about split blog into Chinese and English, see if it matches your original claim.

**Comment by guoqqqi** [comment]
Hi, @Baoyuantop  https://www.docusaurus.cn/docs/i18n/introduction#translation-files-location  Here is a guide to supporting i18n, which I think we should use to solve the problem

**Comment by bzp2010** [comment]
> Hi, @Baoyuantop https://www.docusaurus.cn/docs/i18n/introduction#translation-files-location Here is a guide to supporting i18n, which I think we should use to solve the problem

+1 agree

**Comment by Baoyuantop** [comment]
> Hi, @Baoyuantop https://www.docusaurus.cn/docs/i18n/introduction#translation-files-location Here is a guide to supporting i18n, which I think we should use to solve the problem

OK, I'll try this method.

**Comment by bzp2010** [comment]
> > Hi, @Baoyuantop https://www.docusaurus.cn/docs/i18n/introduction#translation-files-location Here is a guide to supporting i18n, which I think we should use to solve the problem
> 
> OK, I'll try this method.

At the same time, you can also find it in the PR list. I remember some contributors did it.
