### ISSUE TITLE
The version selector dropdown isn't in order by number

### ISSUE THREAD

**Issue by juzhiyuan** [iresty/iresty.github.io#636]
**Actual Behaviour**

Hi, we noticed that the version selector dropdown is not in order by number.

**Expected Behaviour**

We expect that it should be `next/2.10.0/2.9.0/2.8.0/xxx`, but it's `next/2.9.0/2.8.0/2.x.0/2.10`

**Steps to reproduce it**

see https://apisix.apache.org/docs/apisix/architecture-design/apisix

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/2106987/135721187-fe4de09c-63a9-4536-85a0-d850c9c59b7a.png)

**Comment by juzhiyuan** [comment]
cc @guoqqqi to take a look, you could ask help from @bzp2010 or @slorber if needed :)

**Comment by juzhiyuan** [comment]
I see both V1 and V2 Docusarus version selector are correct

- https://v1.docusaurus.io/en/versions
- https://docusaurus.io/

**Comment by guoqqqi** [comment]
OK, let's see
