### ISSUE TITLE
New landing page Issues

### ISSUE THREAD

**Issue by juzhiyuan** [iresty/iresty.github.io#640]
Hi, @1502shivam-singh's all PRs have been merged just now, this issue is to track UI issues :)

Welcome to leave your questions here.

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/135941062-724e4e8f-23ed-4668-9757-367ae7aace34.png)

In the Events part, some links are broken. cc @guoqqqi

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/135941242-4555e0dc-d271-4872-8d79-e9f1286b3a7d.png)

1. This Video is muted, I couldn't play it with audio;
2. How about using YouTube's playlist here? so visitors could watch and play more videos. For Chinese, we could change the Playlist to Apache APISIX's Bilibili.

cc @1502shivam-singh @moonming

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/135941406-275f27cf-27ca-4f0b-8d68-636a4aaccbd2.png)

Hi @liuxiran, I remember that you removed the Logos from Home page, may I know the action context?

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/135941489-970d7493-beea-4a0d-b8db-b507936b9fc3.png)
![image](https://user-images.githubusercontent.com/2106987/135941505-944cbfd2-dcaf-40b6-961d-b0c8610635cc.png)

This is a historical issue, due to the ASF's policy, new users couldn't join #apisix's Slack via fixed invitation link, see https://github.com/apache/apisix/discussions/4932#discussioncomment-1302029

We need to update website's description.

**Comment by 1502shivam-singh** [comment]
> 1. This Video is muted, I couldn't play it with audio;

It wasn't an Yt embed so I just left it on mute, will unmute it 👍

> 2. How about using YouTube's playlist here? so visitors could watch and play more videos. For Chinese, we could change the Playlist to Apache APISIX's Bilibili.

I guess a nice option.

**Comment by juzhiyuan** [comment]
ya, I would suggest using a Playlist here :)

**Comment by 1502shivam-singh** [comment]
> In the Events part, some links are broken. cc @guoqqqi

Oh okay, surprisingly there is no events tab any more ? Where do we link the events to, blog pages ?
EDIT: We have blog posts tagged as events in blogs, maybe add them to events.json ?

**Comment by juzhiyuan** [comment]
> EDIT: We have blog posts tagged as events in blogs, maybe add them to events.json ?

Ya, maybe @Serendipity96 could explain why we remove the Events page and using the events tag 🤔

**Comment by liuxiran** [comment]
> ![image](https://user-images.githubusercontent.com/2106987/135941406-275f27cf-27ca-4f0b-8d68-636a4aaccbd2.png)
> 
> Hi @liuxiran, I remember that you removed the Logos from Home page, may I know the action context?

yep @juzhiyuan , asf has a requirement that the home page of the Apache project website cannot list "powered by" companies, but we can list them on a separate page, so we move all our showcase to the https://apisix.apache.org/showcase

**Comment by juzhiyuan** [comment]
All right, need @1502shivam-singh help to update this case 😆

**Comment by Serendipity96** [comment]
> > EDIT: We have blog posts tagged as events in blogs, maybe add them to events.json ?
> 
> Ya, maybe @Serendipity96 could explain why we remove the Events page and using the events tag 🤔

hi @juzhiyuan @1502shivam-singh, some release notes under the Events tab, but these are duplicates of those under the Release tab. Since release notes under the Release tab are implemented with auto-generation, the release notes under the Events tab seems to be redundant. Thus, remove the release notes under Events tab maybe a  good choice. After removing the redundant release notes from the Events tab, there are only a few event-related documents under the Events tab, which is not sufficient enough to support a tab. So @yzeng25 migrated the article to the blog and added the events tag.

**Comment by juzhiyuan** [comment]
get

**Comment by 1502shivam-singh** [comment]
> hi @juzhiyuan @1502shivam-singh, some release notes under the Events tab, but these are duplicates of those under the Release tab. Since release notes under the Release tab are implemented with auto-generation, the release notes under the Events tab seems to be redundant. Thus, remove the release notes under Events tab maybe a good choice. After removing the redundant release notes from the Events tab, there are only a few event-related documents under the Events tab, which is not sufficient enough to support a tab. So @yzeng25 migrated the article to the blog and added the events tag.

Understood. Though, I think maybe not all events are transferred to the blog section, as then replacing `events` with `blog` in the url should have linked to a specific event, isn't it ?  But instead they lead to a 404 page. Maybe need to recheck on this, i guess.

**Comment by juzhiyuan** [comment]
Yes, and I'm checking and will fix this.

**Comment by Xunzhuo** [comment]
![IMG_0714](https://user-images.githubusercontent.com/48784001/136953173-649f45f5-f2b8-4433-ad1b-a10562d96af6.jpg)
One more thing, in mobile,  two buttons (dark mode and search) are too closed.

**Comment by SkyeYoung** [comment]
Is this still a problem?

**Comment by 1502shivam-singh** [comment]
> Is this still a problem?

Not exactly I suppose, This was put up to act as a single point to post issues related specifically to the redesigned site, just after deployment was done last year. Now that no more **greater issues** seem to prevail so it would be safe to close this I think. 

@juzhiyuan, do you think we can close this now ?

**Comment by juzhiyuan** [comment]
Sure. 😉
