### ISSUE TITLE
feat: add Apache APISIX dashboard playground on website

### ISSUE THREAD

**Issue by Serendipity96** [iresty/iresty.github.io#667]
**Actual Behaviour**

Apache APISIX dashboard demo shows on apache/apisix-dashboard readme, but it is so small. Sometimes I can't find it. 

**Expected Behaviour**

I hope to add a dashboard entrance to the website.

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/23514812/137853081-094b9fbe-269f-4e77-a711-16437c90c186.png)

**Comment by 1502shivam-singh** [comment]
Linking the demo in the text of the below attached shot would be fine. Also, as it's technically supposed to be a **demo**, I think the, username and password step should be skipped altogether, just go straight to the dashboard. 

Above all, if we are able to integrate an "**APISIX playground**" in the website, then I feel adding this **demo** won't even be necessary. I saw this as a checkpoint goal and also an issue, so I feel this should be the definitive action. Linking to the demo dashboard in "logged in" status can be kept until that time. 

![image](https://user-images.githubusercontent.com/57267960/138611321-f4043f58-8440-4c99-88f9-455b9edecfb2.png)

**Comment by DevGautam2000** [comment]
Would like to work on this issue
Please assign this to me

**Comment by DevGautam2000** [comment]
can I get an insight of the feature wanted?

**Comment by 1502shivam-singh** [comment]
> can I get an insight of the feature wanted?

For now, I guess change `go to docs` to `preview`/`demo` and adjust the href to the dashboard demo URL. 
What say, @juzhiyuan.

**Comment by juzhiyuan** [comment]
Hi, @DevGautam2000 @1502shivam-singh I just come back 😅 @Serendipity96 means people want to have a quick check before installing Apache APISIX Dashboard, but there has one 1 entrance on the README that says "demo", it's too hidden, so she wants to add an entrance on our website.

Like https://github.com/apache/apisix-website/issues/667#issuecomment-950389732 says, @DevGautam2000 how about adding the demo button on the Website's Homepage?

**Comment by SkyeYoung** [comment]
@DevGautam2000 Are you still dealing with this issue? If you do not have enough time, I can try to work on this issue.

**Comment by SkyeYoung** [comment]
@juzhiyuan @1502shivam-singh  Do you think it is possible to add a modal (need add a related dependency)? I think it's hard to design a not ugly block to contain the content of demo account.

**Comment by juzhiyuan** [comment]
> @juzhiyuan @1502shivam-singh Do you think it is possible to add a modal (need add a related dependency)? I think it's hard to design a not ugly block to contain the content of demo account.

How about linking a button to Dashboard Demo directly? (with username & password) instead of embedding an iframe

**Comment by SkyeYoung** [comment]
> How about linking a button to Dashboard Demo directly? (with username & password) instead of embedding an iframe

I've created a drft PR, https://github.com/apache/apisix-website/pull/947. I designed a block with some desc and a btn.

I think it's hard to design a NOT UGLY btn with username & password😅

**Comment by juzhiyuan** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/2106987/157004596-61aff0ea-4ac4-4d4b-864c-620f15e35e62.png)

**Comment by SkyeYoung** [comment]
> Something like this?

I don't see any card like design before "Stay updated about APISIX" section in index page. I think we need to maintain design consistency. 

Anyway, I'll try more times.

**Comment by 1502shivam-singh** [comment]
Check out this [prototype](https://www.figma.com/proto/RNpjw3aNENPVidJ1V79Zkg/Dropdown?node-id=2%3A16&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=2%3A16). Click buttons for interaction ideas.

Improvise if you need to.

cc @juzhiyuan  @SkyeYoung

**Comment by SkyeYoung** [comment]
@1502shivam-singh Thx for your prototype. I think it's better for users to get account information without additional operations. 😅 But you gave me some inspiration, I will think about it again.

**Comment by 1502shivam-singh** [comment]
> @1502shivam-singh Thx for your prototype. I think it's better for users to get account information without additional operations. 😅 But you gave me some inspiration, I will think about it again.

Keep it clean and accessible. It's not essential that everything should be thrown at once to the user, the ellipsis style button would raise user's curiosity enough to click and get the demo credentials. 
Also, would like some more ideas from your side.

**Comment by SkyeYoung** [comment]
@1502shivam-singh @juzhiyuan I'm still struggling.😅 Any suggestion to this [prototype](https://www.figma.com/file/vlLJj7YTnWLpzHaZYl20yt/Dashboard-Playground?node-id=0%3A1)?

**Comment by guoqqqi** [comment]
1. We can change `Downloads` or `Go to docs ... ` to ` Request demo` as the docs and Downloads columns are already visible in the navigation.
2. Click the button, The current page pops up with a prompt showing the demo account password
3. Open demo address in a new window
Just a few of my thoughts, free to play ~😆

**Comment by 1502shivam-singh** [comment]
> 1. We can change `Downloads` or `Go to docs ... ` to ` Request demo` as the docs and Downloads columns are already visible in the navigation.

I would say change `Go to docs ...` as `downloads` button is more important I believe in this section.

> 2. Click the button, The current page pops up with a prompt showing the demo account password

This modal idea is preferable to me too.

**Comment by SkyeYoung** [comment]
> > 2. Click the button, The current page pops up with a prompt showing the demo account password
> 
> This modal idea is preferable to me too.

I've already mentioned this. 

> Do you think it is possible to add a modal (need add a related dependency)?

But no reply was received. 😂 It's easy to do it.

**Comment by Baoyuantop** [comment]
How about using a Tooltip component? Just like
<img width="155" alt="image" src="https://user-images.githubusercontent.com/30611190/157784850-47b29467-f361-426c-97e0-d8aa189265f6.png">

Mouse over the button to display the account password, click on the button to jump to the demo.

**Comment by SkyeYoung** [comment]
> How about using a Tooltip component? Just like

I prefer to check the account information is a process that must be passed. Or show the account information directly to the user. :D

**Comment by juzhiyuan** [comment]
I would prefer showing the demo account information directly :D

**Comment by SkyeYoung** [comment]
> I would prefer showing the demo account information directly :D

@juzhiyuan What do you think of [my prototype](https://www.figma.com/file/vlLJj7YTnWLpzHaZYl20yt/Dashboard-Playground?node-id=30%3A11)? I've tried my best. :P

**Comment by juzhiyuan** [comment]
LGTM 🎉 🙌

**Comment by 1502shivam-singh** [comment]
> @juzhiyuan What do you think of [my prototype](https://www.figma.com/file/vlLJj7YTnWLpzHaZYl20yt/Dashboard-Playground?node-id=30%3A11)? I've tried my best. :P

Is the big `GO` like the hover state ?
I am not really sure about it, as it seems really disconnected from the elements in its close proximity because of the large font size.
How about you add some minimal animation, similar to like the arrow animation on the `Go to docs` with the dashboard playground link. 

Better yet, I have a suggestion. How about you animate the gradient on the dashboard playground text with some hover animation. This will hit the sweet spot of being both attention pulling and aesthetic. 

Also, left some feedback in the prototype, please check.

**Comment by SkyeYoung** [comment]
> Is the big `GO` like the hover state ? I am not really sure about it, as it seems really disconnected from the elements in its close proximity because of the large font size. How about you add some minimal animation, similar to like the arrow animation on the `Go to docs` with the dashboard playground link.
> 
> Better yet, I have a suggestion. How about you animate the gradient on the dashboard playground text with some hover animation. This will hit the sweet spot of being both attention pulling and aesthetic.
> 
> Also, left some feedback in the prototype, please check.

@1502shivam-singh Hi, I've add a GIF to my [pr](https://github.com/apache/apisix-website/pull/947) (our preview dead), you can have a look. I'm worried about how to make the animation more lively. You gave me a good suggestion. Thx. 😊

**Comment by SkyeYoung** [comment]
> Also, left some feedback in the prototype, please check.

I checked.

If I change "pass" to "password", it looks less stable (I want its layout to be more triangular). Maybe "passwd" is a better choice, I think. 

Thx for your advice. For convenience, I will update my PR directly (I'm too unfamiliar with figma😅).
