### ISSUE TITLE
speed up Google font loading

### ISSUE THREAD

**Issue by juzhiyuan** [iresty/iresty.github.io#674]
**Actual Behaviour**

Hi, when users in China visit https://apisix.apache.org/ , because our site is using Google font, see https://github.com/apache/apisix-website/blob/master/website/docusaurus.config.js#L643 .

**Expected Behaviour**

🤔 Users in China could use CDN to load fonts, not sure if jsDelivr supports it.

**Comment by juzhiyuan** [comment]
I have submitted 2 PRs to speed up website visit:

- https://github.com/apache/apisix-website/pull/668
- https://github.com/apache/apisix-website/pull/669

**Comment by SkyeYoung** [comment]
I only know this https://u.sb/css-cdn/, It looks very stable. 🤔

**Comment by juzhiyuan** [comment]
It's time to close this issue because I don't have other providers than jsDelivr..
