### ISSUE TITLE
Update Blog list page's style

### ISSUE THREAD

**Issue by juzhiyuan** [iresty/iresty.github.io#677]
**Actual Behaviour**

Hi, we have some feedbacks from users that, the website's default Red theme is hard to visit, here has 2 things to improve:

- [ ] Use a better font color, like #000000?
- [ ] Use an appropriate font size, current one is too big;
- [ ] Have a better sidebar to show all posts, see https://reactnative.dev/blog

**Expected Behaviour**

 

**Steps to reproduce it**

Visit https://apisix.apache.org/blog

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/2106987/138733382-950c450a-67c6-4490-929c-bfbd09b9bcc6.png)

**Comment by BeeBombshell** [comment]
Hey @juzhiyuan , can I work on this issue?

**Comment by bzp2010** [comment]
Hi, @BeeBombshell.
If you would like to try, I will assign issue to you. 👍

**Comment by BeeBombshell** [comment]
I have successfully created a pull request that fixes this issue. @juzhiyuan @bzp2010 kindly review the same.
