### ISSUE TITLE
docs: typo or invalid mark for Docusaurus

### ISSUE THREAD

**Issue by juzhiyuan** [iresty/iresty.github.io#686]
**URL: https://apisix.apache.org/blog/2021/07/25/apachecon-asia**

- [ ] We should load images from CDN
- [ ] Markdown invalid

![image](https://user-images.githubusercontent.com/2106987/139273156-ddfbf4e5-81b1-4bec-b78b-e9e9e4ba8658.png)
![image](https://user-images.githubusercontent.com/2106987/139273248-d90f5d0c-1717-4a37-9535-ec423ecd5f10.png)

**URL: https://apisix.apache.org/blog/2021/06/17/Apache-APISIX-Dashboard-Access-Control-Bypass-Vulnerability-Announcement/**

- [ ] `<! --truncate -->` invalid

**URL: https://apisix.apache.org/blog/2021/10/27/APISIX%20Ingress**

- [ ] Link invalid
![image](https://user-images.githubusercontent.com/2106987/139273689-32316e2f-ee2c-4293-865a-ce01b012f070.png)

cc @yzeng25

**Comment by yzeng25** [comment]
Hi,
the issues listed above are:
1. Missing Shuyang's profile picture
2. <! --truncate --> invalid
3. Invalid link in markdown file
4. Store pictures/images in CDN.

I solved 123 in https://github.com/apache/apisix-website/pull/689, while problem 4 "Store pictures/images in CDN" would  be a good first issue. 

For clarification, is it expected to migrate **all** pictures/images to CDN, or just for pictures/images that would be added in the future, and we can leave previous pictures/images alone?

I can provide step-by-step instructions on the part, but migrating **all** pictures/images would be too much to handle for me. Thus, help from community is needed.

**Comment by yzeng25** [comment]
The steps of importing images to CDN is listed below: 
1. Locate the images that need to be migrate to CDN
2. Download the images to your machine
3. Visit the CDN migration page https://markdown.apiseven.com/#/
4. Click either one of the following buttons to start uploading(single and multiple are both supported).
![image](https://user-images.githubusercontent.com/36651058/139382123-ee122a6d-b1b8-4c31-b782-5a8b5c535600.png)

5. Click this button to continue uploading images, select images you need to upload, 
![image](https://user-images.githubusercontent.com/36651058/139382261-9fdd7680-4590-49c5-bcbe-0746a87b7755.png)

6. After successfully uploaded, a link is generated for each image.
![image](https://user-images.githubusercontent.com/36651058/139382575-addffbac-aef6-4383-8e99-b3782514a633.png)

7. Copy the links and replace the origin links with these link.

**Comment by Ylikj** [comment]
@yzeng25 hi ,let me have  a try, and I want to make sure that I need to replace all the pictures?

**Comment by juzhiyuan** [comment]
Yes

**Comment by yzeng25** [comment]
> @yzeng25 hi ,let me have a try, and I want to make sure that I need to replace all the pictures?

Yes, thanks!

**Comment by juzhiyuan** [comment]
@Ylikj Any update here?

**Comment by Ylikj** [comment]
@juzhiyuan at pr#694,but there is something wrong, I will revise it tonight

**Comment by SkyeYoung** [comment]
Any update here?

**Comment by yzeng25** [comment]
I think this issue is solved long ago by https://github.com/apache/apisix-website/pull/810. We should close it. 
cc @juzhiyuan @bzp2010
