### ISSUE TITLE
Update SkyWalking plugin's docs

### ISSUE THREAD

**Issue by juzhiyuan** [iresty/iresty.github.io#698]
**Actual Behaviour**

see https://apisix.apache.org/docs/apisix/2.9/plugins/skywalking/

Original concontents from `apache/apisix` repo. https://github.com/apache/apisix/edit/release/2.9/docs/en/latest/plugins/skywalking.md
![image](https://user-images.githubusercontent.com/2106987/140004669-cb585a92-36a6-4168-8096-27b9b1a32f2c.png)

**Expected Behaviour**

It should render normally 🤔

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/2106987/140004570-2840ec54-9fc0-4ff5-b2a5-dc89777d5a4f.png)

**Solution**

We need to update docs to remove extra `\`: https://github.com/apache/apisix/edit/release/2.9/docs/en/latest/plugins/skywalking.md

**Comment by namangirdhar16** [comment]
Hi @juzhiyuan can i work on this issue, if yes do assign this to me.

**Comment by juzhiyuan** [comment]
Sure!

**Comment by juzhiyuan** [comment]
@namangirdhar16 Hi, do you need any help?

**Comment by 123liubao** [comment]
Hello, @juzhiyuan I want to work on this, please assign it to me.

**Comment by juzhiyuan** [comment]
Of course 😄

**Comment by 123liubao** [comment]
@juzhiyuan Sorry, I want to confirm that this is a release-2.9 branch problem, the master branch is correct, so which branch should I pull from?

**Comment by juzhiyuan** [comment]
> the master branch is correct

You're right, and let's lead users to use the Latest branch by default 😄 I will close this issue soon.
