### ISSUE TITLE
support to cache to old versions' documents

### ISSUE THREAD

**Issue by bzp2010** [iresty/iresty.github.io#699]
## Background

The current full compilation of the documentation for each project is performed each time a PR merge and scheduled deployment is performed. The older versions of these documents are barely modified, and at the same time, as the versions continue to iterate, the version numbers of the documents become more and more numerous, making the full compilation take longer and longer.

## Suggestion

Add a caching mechanism for older versions of documents so that we don't have to do a full compilation every time.

## Available options
- [ ] GitHub Workflows cache

**Comment by SkyeYoung** [comment]
Did we solve this problem?

**Comment by juzhiyuan** [comment]
No, would you like to implement this? It will speed up building time! Please refer to Docusaurus's site, and it only builds recent versions.

**Comment by SkyeYoung** [comment]
> No, would you like to implement this? It will speed up building time! Please refer to Docusaurus's site, and it only builds recent versions.

Ok, let me complete it.
