### ISSUE TITLE
Remove editUrl for older versioned docs

### ISSUE THREAD

**Issue by juzhiyuan** [iresty/iresty.github.io#700]
**Description**

We use https://docusaurus.io/ to build our website, and it supports showing different version docs.

Example: We have SkyWalking's docs here: https://apisix.apache.org/docs/apisix/2.9/plugins/skywalking/

![image](https://user-images.githubusercontent.com/2106987/140006238-c7be1e68-cbf7-41b4-9b1d-328f08ae6f63.png)

We could use the Version Dropdown to select target version docs. When we visit older version documentation, if we find a typo or incorrect content, we could click the `Edit this page` link to submit a PR to update the contents.

![image](https://user-images.githubusercontent.com/2106987/140006374-e9e4d2f9-cd6b-43d8-8b98-24bc8bfcb65f.png)

**Issue**

When we update older content (mainly documentation), documentations under the released package's contents are different from the lates, we have to release a new package to make sure both package and github branch have the same contents.

**Question**

If we support editing older content, do we need to release a package with the latest docs but older codes?

1. If yes, we have to backport PRs and release a new package;
2. If no, we could support editing older content.

**Comment by juzhiyuan** [comment]
What do you think of this?

cc @bzp2010 @spacewander @iamayushdas @lilien1010 @tokers @tao12345666333 @imjoey

**Comment by spacewander** [comment]
I think we should only allow editing the latest content and submit PR to the source.

**Comment by juzhiyuan** [comment]
I just fixed one issue #704 for Apache APISIX's website, to keep the correct editUrl for versioned docs.

BTW, after discussion with @bzp2010, we two support not updating the older docs 🤔 We encourage users to use the latest Apache APISIX from https://apisix.apache.org/downloads . Maybe we could disable `editUrl` link for older docs.

**Comment by bzp2010** [comment]
Yes, I agree to hide the edit link in the old version of the document.
