### ISSUE TITLE
Need to modify case-sensitive URLs

### ISSUE THREAD

**Issue by yzeng25** [iresty/iresty.github.io#713]
**Actual Behaviour**

 

Currently, the URLs on blogs are case-sensitive, which is resulted from rules set by Apache Server. The case-sensitive URLs become inconvenient when referencing them in other websites and social media. Some might change the upper-case letters in the URLs to lower-case letters automatically. Yet visiting the low-case URLs would return a 404 page.

From the user's aspect (i.e. anyone tries to visit the URLs for the first time) would not be able to access the contents in URLs. And the user experience can be improved.

**Expected Behaviour**

 

1. input the URLs with upper-case letters, it is accessible
2. input the URLs with lower-case letters, it is also accessible

**Steps to reproduce it**
Take https://apisix.apache.org/blog/2021/06/28/why-we-need-Apache-APISIX/ for example:

1. Open your browser.
2. Input the URL:https://apisix.apache.org/blog/2021/06/28/why-we-need-Apache-APISIX/
3. Access the content successfully.
4. Change `Apache-APISIX` to lower-case `apache-apisix`
5. Returns 404.

 

**Screenshots of the issue**
![image](https://user-images.githubusercontent.com/36651058/141045994-7ad04896-1d35-4364-abce-8d948d732e8d.png)
![image](https://user-images.githubusercontent.com/36651058/141046036-20aef59d-3dcf-4119-bbbc-17fb5f19ce00.png)

 

**Would you like to work on the issue?**

yes

**Comment by namangirdhar16** [comment]
@juzhiyuan @yzeng25 if this issue is open, can i work on this?

**Comment by juzhiyuan** [comment]
Wow! Nice to meet you here!!

**Comment by yzeng25** [comment]
> @juzhiyuan @yzeng25 if this issue is open, can i work on this?

Yes, glad to see that :)

**Comment by yzeng25** [comment]
After some researching, there are three ways that could solve this problem, but they all have certain limitations.

1. Use `slug` to customize he last part of the document URL, ref: https://docusaurus.io/docs/docs-introduction#document-id .
2. Rename files directly.
3. Use `plugin-client-redirects` to perform redirections., ref: https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects

Expected Result: 

1. Input the URLs with upper-case letters, it is accessible.
2. Input the URLs with lower-case letters, it is also accessible.

For Method 1, I tested it locally. The `slug` annotation works fine, but only 1 URL works. For example, the original suffix is `/why-we-need-Apache-APISIX`, and then use  `slug` to modify it to `/why-we-need-apache-apisix`. Only the second one is accessible, the original one returns 404.

For Method 2, renaming files can definitely solve the problem. But we would have to find and update all of these links provided to external media, which is not an easy thing to do.

For Method 3,  `plugin-client-redirects` requires manual maintenance and update.

**Comment by juzhiyuan** [comment]
How about this?

- For future posts, we use slug property & lowercase URLs only;
- For the current posts, we could use plugins to redirect historical URLs to lowercase.

**Comment by yzeng25** [comment]
> How about this?
> 
> * For future posts, we use slug property & lowercase URLs only;
> * For the current posts, we could use plugins to redirect historical URLs to lowercase.

Sure!

**Comment by juzhiyuan** [comment]
🥰🥰

**Comment by adarrssh** [comment]
@juzhiyuan is this issue open?

**Comment by juzhiyuan** [comment]
Hi @adarrssh, yes, this issue is still open because some URLs still have this problem. Would you like to try to fix them? by converting URLs from CamelCase to lowercase.

**Comment by adarrssh** [comment]
yes, I would like to work on this, please assign me this issue.

**Comment by yzeng25** [comment]
> yes, I would like to work on this, please assign me this issue.

Cool! Glad to see you solving another issue!

**Comment by adarrssh** [comment]
Hey @yzeng25, is this how we are supposed to add slug to each blogpost?

<img width="899" alt="image" src="https://user-images.githubusercontent.com/85433137/151345933-9d594201-7f0f-4b3c-92a9-d471394f478a.png">

**Comment by yzeng25** [comment]
> Hey @yzeng25, is this how we are supposed to add slug to each blogpost?
> 
> <img alt="image" width="899" src="https://user-images.githubusercontent.com/85433137/151345933-9d594201-7f0f-4b3c-92a9-d471394f478a.png">

Hi @adarrssh, we'd like to avoid using `slug` because it violates our expected result. I would suggest try method 3, the [plugin-client-redirects](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects) to solve it. (see comments/discussion above).

**Comment by mangoGoForward** [comment]
I'd like to tackle it, may need your help, thanks.
/assign

**Comment by yzeng25** [comment]
> I'd like to tackle it, may need your help, thanks. /assign

There you go. Have fun and keep updated timely. Thanks!

**Comment by mangoGoForward** [comment]
I launched the website in local, but did not reproduce this issue, it's so strange, and the screenshot like below:
![image](https://user-images.githubusercontent.com/35127166/155642100-6a228aa6-9e89-40e0-9d74-6dc3856f2c64.png)
![image](https://user-images.githubusercontent.com/35127166/155642114-1f1020e9-fa44-4452-87e7-73783477caa3.png)

@yzeng25

**Comment by mangoGoForward** [comment]
Seems lower-case or upper-case both works well, but on https://apisix.apache.org/ reproduced easily.

**Comment by yzeng25** [comment]
> Seems lower-case or upper-case both works well, but on https://apisix.apache.org/ reproduced easily.

Yes. You can take a look at [plugin-client-redirects](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects). 

My initial thought is to collect all URLs with capitalized letters then use the plugin-client-redirects to convert them, examples can be found at [Example Configuration](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects#ex-config).
