### ISSUE TITLE
support language detection

### ISSUE THREAD

**Issue by juzhiyuan** [iresty/iresty.github.io#743]
**Actual Behaviour**

When users visit apisix.apache.org, our website will serve content in English by default.

**Expected Behaviour**

For users in Chinese, we could provide default Chinese contents for a quick and better involving experiment.

**Solution**

According to https://docusaurus.io/docs/i18n/introduction#i18n-non-goals, Docusaurus will not do language detection, see https://github.com/facebook/docusaurus/issues/5838#issuecomment-955278743 .

Maybe we could use this package? https://www.npmjs.com/package/detect-browser-language

**Comment by SkyeYoung** [comment]
A simple logic to fix this:
1. add a var to localstorage or cookie
2. if the var is false, auto detect browser language, and redirect
3. else if the var is true, follow the user choice

Tip: 
1. we can auto handle the process when user change the language
2. also give a option to allow user re-enable auto redirect

**Comment by SkyeYoung** [comment]
If the logic is ok, pls assign this to me, I'll fix this.

**Comment by LinuxSuRen** [comment]
I still got the English page no matter what the browser language is set.

**Comment by LinuxSuRen** [comment]
I'm wondering if APISix has the feature.

**Comment by juzhiyuan** [comment]
> I'm wondering if APISix has the feature.

This feature has been disabled, you can check codes #970  :)

**Comment by AmazingAng** [comment]
> > I'm wondering if APISix has the feature.
> 
> This feature has been disabled, you can check codes #970  :)

Why this feature is disabled? We are also trying to integrate automatic locale detection on a website based docusaurus.

**Comment by SkyeYoung** [comment]
@AmazingAng Due to the practical needs of the APISIX website, we no longer need this feature. 😅
