### ISSUE TITLE
support more tags for posts

### ISSUE THREAD

**Issue by juzhiyuan** [iresty/iresty.github.io#744]
**Actual Behaviour**

When I visit this post: https://apisix.apache.org/blog/2021/11/12/apisix-datadog , I noticed there has only one Tag called `Technology`. It's too common to use this as the only one tag IMO, and I just checked this page's Meta data, see

![image](https://user-images.githubusercontent.com/2106987/141709370-5ce2485e-8fc5-4b9c-94a7-6815faf95199.png)

**Expected Behaviour**

After comparing with other sites' blogs, I would recommend we fulfill more tags. For the post above, I would recommend using `DataDog,Monitoring,Observability` as the tags.

Not only this post, we should update all posts.

**Comment by adarrssh** [comment]
Hey, can I work on this issue?

**Comment by juzhiyuan** [comment]
Hi @adarrssh, sure!

**Comment by adarrssh** [comment]
So the task is to add (DataDog, Monitoring, Observability) tags in the meta-data and on the  https://apisix.apache.org/blog/2021/11/12/apisix-datadog page as well?

**Comment by adarrssh** [comment]
Hey @juzhiyuan, Can you please elaborate more about this issue, Do I have to add tags like (DataDog, Monitoring, Observability) for this blog post only ( https://apisix.apache.org/blog/2021/11/12/apisix-datadog) or do I have to go through all the blogs of the APISIX website and add tags there too?

**Comment by juzhiyuan** [comment]
Datadog is an example :) For better SEO, we need to improve more necessary Tags for as many posts as possible, you also could find more thoughts from @yzeng25

**Comment by adarrssh** [comment]
Okay, thanks @juzhiyuan 😊.

**Comment by yzeng25** [comment]
Hi @adarrssh , 

Thanks for bringing this up! I have had a conversation with @juzhiyuan about 4 months ago regarding on the similar issue. Here are some thoughts for you, hope it helps.

## What are tags

We use tags to categorize blogs.

## Tags’ mechanism

1. Show up in tags page [1], ordered alphabetically.
2. Gather blogs with the same tag.
3. When click on a certain tag, redirects to a page containing all blogs with the tag

## What tags do we have currently

**Community**: community related, e.g. "How to contribute to an open source project without writing code?"
**Events**: event-related, for example: online live stream, event previews, meetups, and online meeting, etc.
**Interview**: Interviews, e.g., Dr. Yang Li interview, Summer of Programming interview.
**Practical Case**: Best practices, easily confused with Technology. The factors that determine whether an article is a Technology or a Practical Case are: the content of the article and the subject of the description. For example, if the article is about "Running Apache APISIX on xxx platform", then it is a Practical Case; for example, if the article is about technical stuff, "Apache APISIX v.s. Envoy", then it is Technology.
**Release**: Release notes, this is better understood. It should be noted that the release notes inside the blog are polished, while the release notes inside the release are written by developers.
**Security**: Security vulnerability notification and methods to bypass security vulnerabilities, currently there are only two articles, very good to identify, generally have CVE-xxxxxxx is it.
**Technology**: Technical articles, easily confused with Practical Case. The factors that determine whether an article is a Technology or a Practical Case are: the content of the article and the subject of the description. For example, if the article is about "Running Apache APISIX on xxx platform", then it is a Practical Case; for example, if the article is about technical stuff, "Apache APISIX v.s. Envoy", then it is Technology.
**User Case**: User Case, this is also very straightforward. Please tell us how you use Apache APISIX and your feelings about Apache APISIX.

Ref: Blog Contributing Guide[2]

## What tags do we want to have

I would suggest spilt the “Technology” tag into different ones, such as “Ecosystem”, “Observability”,”Monitoring”,”Logging” etc.

As @juzhiyuan suggests in the previous comments, the “Datadog” tag is indeed very precise. But this would result in a tag with only one blog under it. Think about this: if we were to add a tag for each specific brand, community, or product, the tags page [1] would look very messy.

If we take a step back, take it as a sort of “Observability” or “Monitoring”, and add other blogs under the same tag. That is better in my opinion. In other words, we would expect tags’ granary (how fine-grained it is) reach the function field level, but not dive into a specific brand, community, or product.

## More complicated case

Do we need 2 or more tags for a blog? It is technically supported to do so, but it is also hard for maintenance. Take “Datadog” as an example again, if we were to spilt Technology” tag into different ones, such as “Ecosystem”, “Observability”,”Monitoring”,”Logging”, it fits in more than 1 tag. Do we choose the best fit tag or all fitting tags?

## Reference
[1]https://apisix.apache.org/blog/tags

[2]https://apisix.apache.org/docs/general/blog

**Comment by adarrssh** [comment]
Thank you very much @yzeng25 for this detailed explaination.

**Comment by adarrssh** [comment]
Thank you very much @yzeng25 for this detailed explaination.

**Comment by adarrssh** [comment]
<img width="679" alt="image" src="https://user-images.githubusercontent.com/85433137/150118635-24318b58-6093-4192-8770-c25bd8e34741.png">
Hey, I added some  more tags and the output is that all the tags are coming in  the  same line (see image for better reference),
will this be an issue in SEO optimization?.

**Comment by adarrssh** [comment]
I investigated some other blog sites and all of them are using tags in different lines, like this one https://www.freecodecamp.org/news/how-to-build-reusable-components-with-props-in-react/
<img width="706" alt="image" src="https://user-images.githubusercontent.com/85433137/150120791-d4a4285f-0532-45a3-b1d4-54df07d71838.png">

**Comment by juzhiyuan** [comment]
Let's seek help from @yzeng25

**Comment by yzeng25** [comment]
> <img alt="image" width="679" src="https://user-images.githubusercontent.com/85433137/150118635-24318b58-6093-4192-8770-c25bd8e34741.png">
> 
> Hey, I added some more tags and the output is that all the tags are coming in the same line (see image for better reference), will this be an issue in SEO optimization?.

No, that is totally fine :)
