### ISSUE TITLE
The /contribute page broken if current IP hits GitHub API's limitation

### ISSUE THREAD

**Issue by juzhiyuan** [iresty/iresty.github.io#759]
GitHub API has frequency now, while some regions are not able to access the host properly, can we move it to Build CI for that? Will we make this change in the next PR?

_Originally posted by @bzp2010 in https://github.com/apache/apisix-website/pull/758#discussion_r753925848_

**Comment by juzhiyuan** [comment]
If the current IP hits GitHub API's limitation, page is broken 🤔 We could fix it on this way:

1. Update `/contribute` page to read data from a static local JSON file;
2. When CI running, we could run `sync-docs` and add a task to fetch data in CI, and generate a new JSON file.

**Comment by SkyeYoung** [comment]
> 1. Update `/contribute` page to read data from a static local JSON file;
> 2. When CI running, we could run `sync-docs` and add a task to fetch data in CI, and generate a new JSON file.

@juzhiyuan Here's a problem: if we use the generated static data, the data of this page may not be up-to-date. Do you think it's important?

**Comment by bzp2010** [comment]
@SkyeYoung We have crontab set up in our CI to trigger a build every day no matter what, and a PR merge will also trigger a build. Therefore, there is no need to worry about this issue.

**Comment by SkyeYoung** [comment]
@bzp2010 Thx for your reply. I'd like to fix it.

**Comment by bzp2010** [comment]
> @bzp2010 Thx for your reply. I'd like to fix it.

I assign it to you.

**Comment by SkyeYoung** [comment]
@bzp2010 XME. Create a new file or add a new task to the `sync-docs.js` file, which is better?

**Comment by juzhiyuan** [comment]
> @SkyeYoung We have crontab set up in our CI to trigger a build every day no matter what, and a PR merge will also trigger a build. Therefore, there is no need to worry about this issue.

Hi @SkyeYoung, please check https://github.com/apache/apisix-website/blob/master/.github/workflows/deploy.yml#L14

**Comment by SkyeYoung** [comment]
> Hi @SkyeYoung, please check [https://github.com/apache/apisix-website/blob/master/.github/workflows/deploy.yml#L14](https://github.com/apache/apisix-website/blob/master/.github/workflows/deploy.yml?rgh-link-date=2022-03-01T05%3A05%3A26Z#L14)

Thx
