### ISSUE TITLE
combine configuration files into one

### ISSUE THREAD

**Issue by juzhiyuan** [iresty/iresty.github.io#763]
**Actual Behaviour**

Apache APISIX Website has 2 pages around `apisix-*` repos:

- https://apisix.apache.org/docs
- https://apisix.apache.org/downloads

Those 2 pages are generated from 2 different configuration files, some contents are the same so we could combine them into one:

- https://github.com/apache/apisix-website/blob/master/website/config/downloads.js
- https://github.com/apache/apisix-website/blob/master/website/config/docs.js

**Comment by Swastyy** [comment]
Hi @juzhiyuan I see there is a option of Downloads in the `Download` webpage from where a user can directly download whereas its not there in the `Documents` webpage. If you want to combine them then I want to do this. One more thing which one out of `docs.js` and `downloads.js` to keep and which one else to remove?

**Comment by juzhiyuan** [comment]
After considering, how about this?

1. To have a configuration file containing all repos' configuration;
2. To add a property called hiddenOnDocumentList
3. Add a property called latestVersion, latestDownloadLink

**Comment by Swastyy** [comment]
> After considering, how about this?
> 
> 1. To have a configuration file containing all repos' configuration;
> 2. To add a property called hiddenOnDocumentList
> 3. Add a property called latestVersion, latestDownloadLink

I want to work on this, please assign it to me. And what will the hiddenDocumentList do, does it contains some configuration that aren't public or something that is not to be shown in the website?

**Comment by juzhiyuan** [comment]
>  And what will the hiddenDocumentList do, does it contains some configuration that aren't public or something that is not to be shown in the website?

🤔 Yes, you're right, for this case, we don't need that property at all.

**Comment by juzhiyuan** [comment]
After consideration, I think it will increase complexity, I'm going to close this.
