### ISSUE TITLE
Add the DockerHub links on Downloads page

### ISSUE THREAD

**Issue by juzhiyuan** [iresty/iresty.github.io#767]
**Actual Behaviour**

We have a download page here[1], it supports the latest version of source codes, we could provide more ways to download package 😄

[1] https://apisix.apache.org/downloads

**Solution**

We support RPM/Docker/Helm ways to get package, we could generate or add their links on the download page.

**Comment by oil-oil** [comment]
@juzhiyuan  I want to undertake this task, does the new download link need to be added to the download item?
<img width="211" alt="image" src="https://user-images.githubusercontent.com/57465570/154386584-1b78590d-d57e-48c1-9b00-6cbcf0ebd27c.png">

**Comment by guoqqqi** [comment]
> does the new download link need to be added to the download item?

Maybe we can do that? Any better suggestions? 😂
![image](https://user-images.githubusercontent.com/72343596/154396500-b720f9a6-6f88-41e5-983c-f5431c9d5265.png)

**Comment by Baoyuantop** [comment]
I think it is good to arrange directly downward.

**Comment by oil-oil** [comment]
Can you provide the correct url related to RPM/Docker/Helm?

**Comment by juzhiyuan** [comment]
For Docker, it's https://hub.docker.com/r/apache/apisix-dashboard
