### ISSUE TITLE
Default version show release, not current master, in how to build document

### ISSUE THREAD

**Issue by hongbinhsu** [iresty/iresty.github.io#773]
**Actual Behaviour **
In http://apisix.apache.org/zh/docs/apisix/how-to-build default show release version，not current master;
for example https://repos.apiseven.com/packages/centos/7/x86_64/apisix-2.11.0-0.el7.x86_64.rpm is 404 now.

**Expected Behaviou **
Need default show current master version, avoid misunderstandings.

**Comment by SkyeYoung** [comment]
@juzhiyuan In fact, default version is current release version, there's nothing wrong with that. I think this issue should be closed.

**Comment by juzhiyuan** [comment]
Hi, do you mean https://apisix.apache.org/docs/apisix/next/how-to-build?
