### ISSUE TITLE
Prometheus doc 'Grafana dashboard meta ' file link is broken

### ISSUE THREAD

**Issue by huang-x-h** [iresty/iresty.github.io#782]
**Actual Behaviour**

`prometheus` plugin doc click `Grafana dashboard 元数据 ` is broken

 

**Expected Behaviour**

https://cdn.jsdelivr.net/gh/apache/apisix@release/2.11/docs/assets/other/json/apisix-grafana-dashboard.json

 

**Steps to reproduce it**

 

in `en` doc click `Grafana dashboard meta', the link is  https://github.com/apache/apisix/blob/master/docs/assets/other/json/apisix-grafana-dashboard.json

in `zh` doc click `Grafana dashboard 元数据 `, the link is  https://apisix.apache.org/zh/assets/other/json/apisix-grafana-dashboard.json

**Screenshots of the issue**

![1638323020(1)](https://user-images.githubusercontent.com/381860/144156535-363f4842-1051-42d1-9401-4b307dc4881b.png)

 

**Would you like to work on the issue?**

yes, are the website assets files use the `jsdelivr` ? i can't find how to change the url in markdown files.

**Comment by juzhiyuan** [comment]
Hi, I just checked the original Markdown file:

- https://github.com/apache/apisix/edit/release/2.11/docs/en/latest/plugins/prometheus.md
- https://github.com/apache/apisix/edit/release/2.11/docs/en/latest/plugins/prometheus.md

![image](https://user-images.githubusercontent.com/2106987/144255174-21cddb9a-df3b-455d-b8bc-9cfa5ba856db.png)

![image](https://user-images.githubusercontent.com/2106987/144255202-2e9db06a-c475-492f-9d1e-5fe475b208e5.png)

We could fix it by using an absolute URL :)

**Comment by huang-x-h** [comment]
Should i send a PR or you just fixed it ？ not diffcult :) @juzhiyuan

**Comment by juzhiyuan** [comment]
@huang-x-h may need your help here 🙈🙈

**Comment by juzhiyuan** [comment]
fixed https://apisix.apache.org/zh/docs/apisix/plugins/prometheus/
