### ISSUE TITLE
need "Approve and run" when first-time contributors submit a PR

### ISSUE THREAD

**Issue by juzhiyuan** [iresty/iresty.github.io#785]
**Actual Behaviour**

![image](https://user-images.githubusercontent.com/2106987/144425902-1059f48a-18b3-4316-b742-e99432ba3b3b.png)

First-time contributor needs approve and run to check what's the status of CI

**Expected Behaviour**

PR could run CI automatically, so developers could see what happened to that PR. We need to ask help from ASF Infra.

**Comment by juzhiyuan** [comment]
cc @lxm to know this.

**Comment by lxm** [comment]
I've got a workaround for limited cases.
```
1. fork the project
2. enabled the actions (actions is disabled by default for fork repos)
3. create pr both to upsteam repo and personal forked repo
4. actions will be triggered  in personal repo
```

this can be a workaround for actions with out secrets

**Comment by juzhiyuan** [comment]
Good!

**Comment by SkyeYoung** [comment]
Is this still a issue? I've forgotten my original PR.

**Comment by juzhiyuan** [comment]
No, this is enabled by the ASF.
