### ISSUE TITLE
Keep the same language in blog

### ISSUE THREAD

**Issue by juzhiyuan** [iresty/iresty.github.io#792]
**Actual Behaviour**

Take https://apisix.apache.org/blog/2021/11/30/use-apisix-ingress-in-kubesphere/ as an example, it's written in English but with the image in Chinese 🤔 

**Expected Behaviour**

I would suggest using the same language in the posts.

related issue https://github.com/dapr/docs/issues/1972

**Comment by juzhiyuan** [comment]
cc @yzeng25 @SylviaBABY

**Comment by juzhiyuan** [comment]
**Update**

I noticed our Medium has some images in Chinese 🤔 We will improve them **in the future**.

http://medium.com/@apacheapisix

**Comment by yzeng25** [comment]
See https://github.com/apache/apisix-website/issues/1153#issuecomment-1198159303
