### ISSUE TITLE
The apisix-website return 503 error

### ISSUE THREAD

**Issue by takumi913** [iresty/iresty.github.io#823]
**Actual Behaviour**

When I visited `https://apisix.apache.org/zh/docs/apisix/next/getting-started`, get a 503 error.

 

**Expected Behaviour**

 
Return a normal html

**Steps to reproduce it**

visit `https://apisix.apache.org/zh/docs/apisix/next/getting-started`
 

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/38528079/147305441-cf544a3f-5806-4ba0-bfa5-a1ab75f13275.png)

![image](https://user-images.githubusercontent.com/38528079/147305458-1882b3ca-9114-4046-9788-84d1c210dfc3.png)

 

**Would you like to work on the issue?**

**Comment by juzhiyuan** [comment]
resolved by ASF Infra.
