### ISSUE TITLE
docs: use Canary Release instead of Grayscale

### ISSUE THREAD

**Issue by juzhiyuan** [iresty/iresty.github.io#833]
**Actual Behaviour**

Hi, in our posts, we use `Grayscale` to refer to `灰度发布`. e.g https://apisix.apache.org/blog/2021/10/09/apisix-ingress-techblog/

**Expected Behaviour**

Actually, it should be `Canary Release`. We need to replace any text under `Blog`[1] with `grayscale` to `canary release` :)

[1] https://github.com/apache/apisix-website/tree/master/website/blog

**Comment by yzeng25** [comment]
Hi, 

`grayscale`, `Grayscale`, `gray-scale`, `Gray-scale`, `gray scale`, and `Gray scale` are replaced accordingly in https://github.com/apache/apisix-website/pull/832
