### ISSUE TITLE
Correct choice of words in Getting started.

### ISSUE THREAD

**Issue by Anita-ihuman** [iresty/iresty.github.io#866]
**Actual Behaviour**
I also noticed that the "Getting started" component references  “article” rather than Documentation. 
 

**Expected Behaviour**
This section of the Documentation should be carefully reviewed and improved upon to become self-explanatory to users reading through. The words should be corrected too
 

**Steps to reproduce it**

 

**Screenshots of the issue**
![Screenshot 2022-01-05 at 11 43 43](https://user-images.githubusercontent.com/62384659/152497082-b4125ac2-a869-4c96-ba46-cf547a272806.png)

 

**Would you like to work on the issue?**

**Comment by juzhiyuan** [comment]
> I also noticed that the "Getting started" component references “article” rather than Documentation.

Hi @Anita-ihuman, I'm not clear what's `article rather than docs` 🤔 Could you please provide more details?

**Comment by Anita-ihuman** [comment]
The documentation has a recurring use of the word "article", instead of documentation.

**Comment by 123liubao** [comment]
I want to work on this , could you please assign it to me.

**Comment by Anita-ihuman** [comment]
@juzhiyuan if you can, please assign this task to @123liubao
