### ISSUE TITLE
A strange problem caused by switching color modes in multiple tabs

### ISSUE THREAD

**Issue by SkyeYoung** [iresty/iresty.github.io#871]
**Actual Behaviour**

If you open the docs in another tab and switch to dark mode, when you return to the home page in the original tab, the home page will also switch to dark mode

**Expected Behaviour**

Maybe it should be reset to light mode? Or, I think it's possible to add a toggle button to the homepage as well. It's also good if the homepage has a good dark mode.

**Steps to reproduce it**

It's hard to describe, and I'll give a gif.

**Screenshots of the issue**

![apisix-problem](https://user-images.githubusercontent.com/48400568/152977755-b17e8e9b-efa4-4afb-b31e-82238557c808.gif)

**Would you like to work on the issue?**

Yes, but before that, I need to know the community's opinion.

**Comment by Baoyuantop** [comment]
I noticed that after switching to dark mode on other pages, it automatically changes back to the light mode when I return to the home page of the site.

**Comment by SkyeYoung** [comment]
@Baoyuantop in multiple tabs? I found that only in the same tab is the case you described. I will give my chrome info below. 

<details>
<summary>Chrome Info</summary>


Google Chrome | 97.0.4692.99 (Official Build) (64-bit)
-- | --
Revision | d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}
OS | Linux
JavaScript | V8 9.7.106.19
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
Command Line | /opt/google/chrome/google-chrome --enable-crashpad --flag-switches-begin --flag-switches-end --origin-trial-disabled-features=CaptureHandle

</details>

Although I only give the infomation about Chrome in Linux, I also reproduced this problem in Windows. In fact, the GIF was recorded in Windows.

**Comment by SkyeYoung** [comment]
@Baoyuantop Maybe you should take a closer look at the GIF I recorded (note my switch between the two tabs), and I've reproduced this issue on my phone (also Chrome)

**Comment by 1502shivam-singh** [comment]
> I noticed that after switching to dark mode on other pages, it automatically changes back to the light mode when I return to the home page of the site.

It is intended, please check this - https://github.com/apache/apisix-website/issues/872#issuecomment-1033831539

> It's also good if the homepage has a good dark mode.

Sure could be, but will need some time to decide color palettes for keeping a consistent visual design. So, based on prioritizing I think if one has time can take up this, or we could delegate this.

**Comment by 1502shivam-singh** [comment]
> If you open the docs in another tab and switch to dark mode, when you return to the home page in the original tab, the home page will also switch to dark mode

What I observe is that the dark mode is switching to light mode, as is programmed (only not fast, surprisingly). Reason for this I guess is that the dark mode context of the documentation section (in other tab) is stored in localstorage of browser and the site opening on other tab picks it up as theme. 
But, to maintain light mode on homepage, the code resets the theme using the docusaurus's useThemeContext(), 
https://github.com/apache/apisix-website/blob/2b43e5aeff92c2aabac14a540426de555cef238d/website/src/pages/index.js#L28-L41

Only issue, is that this switch is slow on your system, but seems smooth on mine 🤔

**Comment by Baoyuantop** [comment]
OK, I found the point @1502shivam-singh.
 Following exactly the steps in the gif provided by SkyeYoung, the site's homepage ended up in the dark mode.

**Comment by SkyeYoung** [comment]
@1502shivam-singh Sorry, my English is very poor. Maybe my description misled you.

I mean, first open the home page in a tab, and open the document navigation page in this tab, then right-click to open the document of apisix in the new tab, switch to the dark mode, then click the first tab, and click back to the home page, You will find that the home page is not reset to light mode as expected. (yes, I know there are some codes in the program to reset back to light mode)

I reproduced this behavior on different devices (maybe not because my system is too slow) :D

**Comment by 1502shivam-singh** [comment]
Yes ! you are right. This behaviour is rather erratic. Feel free to fix it.
