### ISSUE TITLE
UI problem of switching color mode in mobile browser

### ISSUE THREAD

**Issue by SkyeYoung** [iresty/iresty.github.io#872]
**Actual Behaviour**

The switch keep show dark mode, when reset to light mode

**Expected Behaviour**

Actually, color mode switch should not show (As shown in the view on the large screen). But if we need to keep this switch in the phone, we need to refresh the state of the switch after resetting back to light mode.

**Steps to reproduce it**

As shown in GIF below

**Screenshots of the issue**

![20220209_114520](https://user-images.githubusercontent.com/48400568/153120268-f17eb869-ff5f-4f5c-9e12-a216a27e6b68.gif)

**Would you like to work on the issue?**

Yes, but I don't have time now.

**Comment by 1502shivam-singh** [comment]
NOTE: For anyone who would want to work on this -

- The intended working from my side was to keep the dark mode only for documentation section of the site, not the homepage (reason for this is related to prioritizing, have delegated this for now). This is why dark mode swatch disappears on desktop devices. 

So, the work that needs to be done to actually resolve this, is to make the dark mode swatch disappear on mobile (which is not happening now, a miss from my side !)
