### ISSUE TITLE
The 2.12.1 version source package is missing

### ISSUE THREAD

**Issue by oil-oil** [iresty/iresty.github.io#873]
Follow the operations in the documentation and find that the source package of version 2.12.1 is missing

<img width="978" alt="image" src="https://user-images.githubusercontent.com/57465570/153325924-ed5a68ee-b185-40ba-b5e9-4d2256a20ef3.png">

The screenshot of the page in the apache website is as follows：
<img width="512" alt="image" src="https://user-images.githubusercontent.com/57465570/153325897-659c14cc-c9cc-454f-bc4d-8222dff1b79c.png">

**Comment by takumi913** [comment]
The 2.12.1 version has released.

<img width="773" alt="image" src="https://user-images.githubusercontent.com/38528079/153374074-e96b8a69-084c-4414-be98-7e8a065f6174.png">

**Comment by takumi913** [comment]
Can we close this issue? @juzhiyuan
