### ISSUE TITLE
Improving the Blog Contributing Guide page

### ISSUE THREAD

**Issue by BeeBombshell** [iresty/iresty.github.io#879]
**Actual Behaviour**

While going through the Blog Contributing Guide page, I found various typos and grammatical errors that need to be addressed and fixed.

**Expected Behaviour**

 Fix the issues on the Blog Contributing Guide page. Record similar issues, if they exist, on any other page.

**Steps to reproduce it**

The section of the website under consideration can be accessed using the following link.
https://apisix.apache.org/docs/general/blog

**Screenshots of the issue**

<img width="960" alt="image" src="https://user-images.githubusercontent.com/53828745/153769281-184e0a61-c990-4fe3-866d-9d617700de18.png">

**Would you like to work on the issue?**

 Yes, I would like to work on this issue.

**Comment by BeeBombshell** [comment]
Hey @juzhiyuan, @shuaijinchao please review the issue... I'd like to work on it :)

**Comment by shuaijinchao** [comment]
PRs are very welcome, but can you give an example of the current problem?

**Comment by BeeBombshell** [comment]
@shuaijinchao For instance, the word "submit" has been misspelled in the above screenshot. Similarly, there are some other typos and grammatical mistakes. To fix this issue, I'm planning to check the content for any shortcomings, and amend them...

**Comment by shuaijinchao** [comment]
@BeeBombshell Great, welcome to fix it in a PR.

**Comment by BhavyaT-135** [comment]
Hi @juzhiyuan, @shuaijinchao, @BeeBombshell I found similar issues on the Contributor Guide page as well. I would like to work on that and fix the documentation. Should I file a new issue or submit a PR in this issue itself?

**Comment by juzhiyuan** [comment]
Hi @BhavyaT-135, you could create a PR to fix it directly, and please link to this issue.

**Comment by BhavyaT-135** [comment]
Sure @juzhiyuan, I will create the Pull Request ASAP :)

**Comment by shuaijinchao** [comment]
@BhavyaT-135 I saw the PR and it was great
