### ISSUE TITLE
We no longer reserve these articles in README?

### ISSUE THREAD

**Issue by tokers** [iresty/iresty.github.io#908]
We no longer reserve these articles in README?

_Originally posted by @tokers in https://github.com/apache/apisix/pull/6445#r814623925_

**Comment by juzhiyuan** [comment]
Hi, @tokers, most of the removed contents are also put in blogs.

**Comment by tokers** [comment]
> Hi, @tokers, most of the removed contents are also put in blogs.

Got it.
