### ISSUE TITLE
[bug]: APISIX LTS SHA512 links error

### ISSUE THREAD

**Issue by guoqqqi** [iresty/iresty.github.io#909]
### Current State

**Description of the current state/issue**:
LTS download link duplicated
![image](https://user-images.githubusercontent.com/72343596/155913657-643635c1-ade1-42d5-8642-114a8954bb9c.png)

**Link to the page**:
https://apisix.apache.org/downloads
**Screenshots (if relevant)**:

### Desired State

**Description of the change you are proposing**:
Update the correct SHA512 links 
`https://downloads.apache.org/apisix/2.10.4/apache-apisix-2.10.4-src.tgz.asc`
to `https://downloads.apache.org/apisix/2.10.4/apache-apisix-2.10.4-src.tgz.sha512`

**Comment by SkyeYoung** [comment]
I'd like to try to fix this.
