### ISSUE TITLE
[Docs]: SEO for blogs URI, title and content 

### ISSUE THREAD

**Issue by moonming** [iresty/iresty.github.io#914]
### Current State

The title and content of the blog article do not consider SEO, for example, there are no keywords such as `API gateway` and `ingress`, and the content is mainly technical.
That way, it's hard to find these if users don't search for Apache APISIX.
For example, https://apisix.apache.org/blog/2022/02/21/nacos, from URI, title to the content, there is no keyword for API gateway. Other articles have similar issues.

### Desired State

We need to go through all blogs and other content completely, SEO optimization from URI, title and content

**Comment by yzeng25** [comment]
Attempted to solve in https://github.com/apache/apisix-website/pull/945, finally completed in https://github.com/apache/apisix-website/pull/1141 and https://github.com/apache/apisix-website/pull/1158.
