### ISSUE TITLE
[Docs]: Allow single-language blog without creating 404

### ISSUE THREAD

**Issue by yzeng25** [iresty/iresty.github.io#920]
### Current State

**Description of the current state/issue**:

When submitting a pull request to add a new blog to the website's blog section, usually we need to submit 2 files, one in English and the other in Chinese.

As the community grows, blog in both languages are becoming more diverging than before. Thus, writing and submitting blogs in single-language is the trend.

But the actual behavior is that: when submitting an English blog, and clicking the language conversion button on the top-right corner, it would jump to the default 404 page. I am wondering if there is any chance to enhance the reading experience on this part. 

### Desired State

**Description of the change you are proposing**:
1. Submit a pull request with blog written in English or Chinese.
2. Visit the blog, and click language switch on the top right corner of the preview (or actual website page after it gets merged).
3. Stay on the same page.

### Would you like to fix this issue?

_No_

**Comment by oil-oil** [comment]
@yzeng25 😀 Can you provide a link to an example?

**Comment by yzeng25** [comment]
> @yzeng25 😀 Can you provide a link to an example?

Not really. When this issue was found, we did translations to fix it. The best way to reproduce it is to create a pull request and use the preview link to reproduce this issue.

**Comment by juzhiyuan** [comment]
Last year, we translated nearly all Chinese blogs to the English version; here is one PR[1]. 

@moonming, I have one question: which language will we use on the Apache APISIX website? If most coming contents are **only in Chinese,** We will have the same problem as last year.

[1] https://github.com/apache/apisix-website/pull/659/files

**Comment by juzhiyuan** [comment]
@moonming @yzeng25 @SylviaBABY @nfrankel @Anita-ihuman @avinal @1502shivam-singh @sshniro @iamayushdas  @bzp2010 @liuxiran @SkyeYoung

Before reaching an agreement on this discussion, I would insist on all Documentation PRs needed to **contain the English version at least**.

**Comment by juzhiyuan** [comment]
Back to this issue, we're building an i18n website; according to Docusaurus's Documentation[1], it will throw 404 if you switch a language without specific translation. Of course, we could prevent users from switching language, but:

1. We need to hack codes to Docusaurus, I don't want to do hacks, or it's hard to update Docusaurus from upstream.
2. If I share a Chinese-only blog with Twitter, it will get 404 if people who don't speak Chinese switch a language.

[1] https://docusaurus.io/docs/i18n/introduction

**Comment by iamayushdas** [comment]
IMO we should only be focusing on English blogs as we all know that the community is going global very fast so for that sake we should switch our content in english only from now. And also we should encourage other blog writers for english content as well.

**Comment by juzhiyuan** [comment]
We keep English contents by default here[1] and other languages contents here[2]. It's ok to submit one-language-only content to this repo (e.g., Chinese only event/contents), then you need not focus on why it will throw 404. It's the default action from Docusaurus, and it's reasonable to have 404 because we don't have other language contents.

If you want to do hacks and show a tip like "This content is Chinese only" and prevent switching language by clicking the switch bar or hiding it directly, those hacks will mess up this repo.

[1] https://github.com/apache/apisix-website/tree/master/website/blog
[2] https://github.com/apache/apisix-website/tree/master/website/i18n/zh/docusaurus-plugin-content-blog

**Comment by yzeng25** [comment]
To sum up the above, the best solution is to deal with it as it is if we don't want to hack it and have upgrading problems in the future. Is it correct?

**Comment by juzhiyuan** [comment]
>  the best solution

I don't have the best solution here, and waiting fore more replies.

**Comment by moonming** [comment]
I think the language switch button can be removed and changed to "Chinese Blog". that's it

**Comment by juzhiyuan** [comment]
After removing the language switcher, what about Documentation in Chinese?

**Comment by avinal** [comment]
> After removing the language switcher, what about Documentation in Chinese?

We can keep them in the archive for now, until we are sure that nothing is missing.

**Comment by yzeng25** [comment]
> > After removing the language switcher, what about Documentation in Chinese?
> 
> We can keep them in the archive for now, until we are sure that nothing is missing.

I am sure this will make Chinese readers upset.

**Comment by moonming** [comment]
> After removing the language switcher, what about Documentation in Chinese?

Not removed, it's replaced. 
All Chinese blogs will be on a separate page.
Chinese and English are completely independent blogs, so there is no language switch button, no 404 error.

**Comment by SkyeYoung** [comment]
> All Chinese blogs will be on a separate page.
> Chinese and English are completely independent blogs, so there is no language switch button, no 404 error.

@moonming Why not just mix them in one page? Like https://antfu.me/posts. Use tags to distinguish. 

It will make the number of articles look more, users can also filter through specific language tags. :D

**Comment by moonming** [comment]
> > All Chinese blogs will be on a separate page.
> > Chinese and English are completely independent blogs, so there is no language switch button, no 404 error.
> 
> @moonming Why not just mix them in one page? Like https://antfu.me/posts. Use tags to distinguish.
> 
> It will make the number of articles look more, users can also filter through specific language tags. :D

Because there are a lot of duplicate articles, just in different languages. For example, a Chinese reader sees a mixed page, titles and content in various languages will give him a very cluttered feeling

**Comment by yzeng25** [comment]
> > All Chinese blogs will be on a separate page.
> > Chinese and English are completely independent blogs, so there is no language switch button, no 404 error.
> 
> @moonming Why not just mix them in one page? Like https://antfu.me/posts. Use tags to distinguish.
> 
> It will make the number of articles look more, users can also filter through specific language tags. :D

We've had that months ago, it is a mess and just don't look right. So I would say no to this option.

**Comment by SkyeYoung** [comment]
> it is a mess and just don't look right

Maybe just lack a good UI design :D

Anyway, do what you want.

**Comment by juzhiyuan** [comment]
Hi @sshniro @iamayushdas @Yiyiyimu @SylviaBABY @Anita-ihuman @leslie-tsang @tokers @totemofwolf @nfrankel @Boburmirzo @EmilyKeer what do you think about this ticket?

**Comment by SylviaBABY** [comment]
After reading the above replies, I think maybe we can do this:

Separate Chinese and English into two pages. From today, Chinese articles will no longer be translated, and only Chinese will be sent; English content will also be sent directly to English pages.

But this will cause the content of the output on both sides to be inconsistent, and what English readers see is different from that of Chinese readers; Of course, if readers use translation software to read by themselves, there is no problem, but it will take some extra time.

So I think Ming's opinion can be adopted, that is, all the current articles are directly divided into two pages in Chinese and English, and the subsequent articles can be published in the author's first language type (no translation required). But the folder structure of the website will adjust, don't know if it will affect other things.

**Comment by iamayushdas** [comment]
I too agree with what @moonming Sir has said.
Separating the chinese and english blogs would be better for now.
@juzhiyuan

**Comment by leslie-tsang** [comment]
Personally, I would prefer to have a **native** speaker friendly docs rather than a precisely synchronised but poorly understood one. 

Agree with @moonming , It will be better separating the chinese and english blogs for now. :)

**Comment by GeekEmily** [comment]
+1 to @leslie-tsang 's comment. Users and contributors care more about the quality of the content.

**Comment by Yiyiyimu** [comment]
We could notice that, what the official documentation of Docusaurus is supporting is that: it uses [Crowdin](https://crowdin.com/), a volunteering out-sourcing translation platform to support i18n, and use this way to let the community contribute their own translation, so maintainers won't worry about that anymore. Another benefit of it is that it would fall back to the default language if another possible language is unsupported yet, so users could directly use translation tools to do their own work without seeing 404.

Two possible problems of it include that partial translation could be shown on the i18n page, which might make the translation tool confused (as you could see on ref 1), and also migrating our current i18n system to Crowdin could be tiring.

Ref:
[1] https://www.docusaurus.cn/blog/2022/01/24/docusaurus-2021-recap

**Comment by moonming** [comment]
any update？

**Comment by membphis** [comment]
@SkyeYoung would you have time to fix this issue?

**Comment by SkyeYoung** [comment]
> @SkyeYoung would you have time to fix this issue?

Yes, I can give it a try.

**Comment by yzeng25** [comment]
After discussion with @moonming and @SylviaBABY , the following changes are needed for apisix-website:

1. Remove the Language Switch button from the top right corner of the page. Replace it with the "Blog/博客" button. This button will be displayed in the top right corner of the blog overview page and every blog page. Click this button to jump to the blog overview page in a language other than this one. 
2. The url of each post cannot be changed.
3. Support separate English and Chinese content.
4. Submitting a PR with English blog only, the preview should show English blog content
5. Submitting a PR with Chinese blog only, the preview should show Chinese blog content
6. Submitting a PR with English and Chinese blogs, preview should show English blog and Chinese blog content

**Comment by juzhiyuan** [comment]
1. Just to make sure, do you mean remove the Language Switcher from ALL pages or ONLY Blog-related pages?
2. The navbar has already contained the `Blog` button, no need to add another one.
3. `The url of each post cannot be changed.`: any details?
4. After removing the language switcher, visitors will only see one specific language content, unless updating the URL manually.

**Comment by yzeng25** [comment]
> Just to make sure, do you mean remove the Language Switcher from ALL pages or ONLY Blog-related pages?

ONLY Blog-related pages.

> The navbar has already contained the Blog button, no need to add another one.

Consider it as a still a  Language Switch button, but only jumps to the blog summary page. This can avoid jumps to 404s when submitting a PR with one language contents.

> The url of each post cannot be changed.: any details?

This is just in case when Docusaurus does not work out. If we were to switch to another framework, say Hugo, I'd like to keep urls the same. Otherwise the SEO work we've done would be wasted.

> After removing the language switcher, visitors will only see one specific language content, unless updating the URL manually.

This exactly what we want. cc @moonming

**Comment by SkyeYoung** [comment]
> Consider it as a still a Language Switch button, but only jumps to the blog summary page. This can avoid jumps to 404s when submitting a PR with one language contents.

I accept this. But it's hard to remove / replace the locale dropdown without change the code of docusaurus. We can just change the behavior of locale dropdown in blog page.

> Submitting a PR with English blog only, the preview should show English blog content
> Submitting a PR with Chinese blog only, the preview should show Chinese blog content
> Submitting a PR with English and Chinese blogs, preview should show English blog and Chinese blog content

This is a very time-consuming thing. I don't have time to do this until I solve the problem of construction speed. 

IMO, I prefer to give a friendly tip 'help us translate' to users who need Chinese on 404 page.

**Comment by yzeng25** [comment]
> I accept this. But it's hard to remove / replace the locale dropdown without change the code of docusaurus. We can just change the behavior of locale dropdown in blog page.

Sounds good.

We can ask others to help on the second part.

**Comment by juzhiyuan** [comment]
> IMO, I prefer to give a friendly tip 'help us translate' to users who need Chinese on 404 page.

Agree. According to https://docusaurus.io/blog/2021/03/09/releasing-docusaurus-i18n, Docusaurus supports 3 ways to achieve i18n. We could support `Crowdin`.

Another thing is:

1. First, please clearly expect the problem to be solved.
2. Second, there are two categories of users for this site: visitors and contributors. So, whose problem is the current issue solving?
3. Finally, I would not recommend modifying the site until there is a consensus.

**Comment by SkyeYoung** [comment]
> 3\. Finally, I would not recommend modifying the site until there is a consensus.

Agree, we need further discussion.
