### ISSUE TITLE
feat: add user page

### ISSUE THREAD

**Issue by tzssangglass** [iresty/iresty.github.io#944]
### Current State

Now we have the powered-by page, which already corresponds to some icons. But they don't look uniform enough.

powered-by: https://github.com/apache/apisix/blob/master/powered-by.md

### Desired State

Maybe we can refer to the user cases design of skywalking website: https://skywalking.apache.org/users/

link: https://github.com/apache/skywalking-website/blob/master/data/users.yml

**Comment by oil-oil** [comment]
Do we need to add a new page in apisix website to show powered by ?

**Comment by tzssangglass** [comment]
> Do we need to add a new page in apisix website to show powered by ?

I don't think so, maybe we need to modify apisix powered-by.md to provide accurate data, but still be displayed in APISIX WebSite.

**Comment by SkyeYoung** [comment]
> > Do we need to add a new page in apisix website to show powered by ?
> 
> I don't think so, maybe we need to modify apisix powered-by.md to provide accurate data, but still be displayed in APISIX WebSite.

@tzssangglass Looks like we already have a page https://apisix.apache.org/zh/showcase. Maybe we just need change the powered-by.md? And should we use a more structural file like yaml or json to replace the powered-by.md?

**Comment by tzssangglass** [comment]
> @tzssangglass Looks like we already have a page [apisix.apache.org/zh/showcase](https://apisix.apache.org/zh/showcase). Maybe we just need change the powered-by.md? And should we use a more structural fil

Yes, maybe we can just move powered-by to the apisix-website directory and change his format. cc @juzhiyuan PTAL

**Comment by Baoyuantop** [comment]
Current the data save in https://github.com/apache/apisix-website/blob/master/website/static/data/showcases.json , We need to synchronize this file.

**Comment by SkyeYoung** [comment]
> We need to synchronize this file.

I think we may just need one file (like skywalking), or add the link of `showcases.json` to `powered-by.md` 🤔

**Comment by moonming** [comment]
by the way, The logos in [apisix.apache.org/zh/showcase](https://apisix.apache.org/zh/showcase) are not clear

**Comment by hanzhenfang** [comment]
ok i will try my best to completed the issuse

**Comment by hanzhenfang** [comment]
> by the way, The logos in [apisix.apache.org/zh/showcase](https://apisix.apache.org/zh/showcase) are not clear

ok ,i  think i can try to completed it!

**Comment by guoqqqi** [comment]
@hanzhenfang It may be necessary to adjust the style of the image, and for some images that are still unclear, they need to be replaced with clearer ones. If you encounter any problems, feel free to drop me a line ～ Thanks 😄

**Comment by guoqqqi** [comment]
> I think we may just need one file (like skywalking), or add the link of `showcases.json` to `powered-by.md` 🤔

+1 Now we need to maintain two files, `showcases.json`, `powered-by.md`. To be honest, it's a bit complicated to make sure the two files are the same every time we update it

**Comment by hanzhenfang** [comment]
> @hanzhenfang It may be necessary to adjust the style of the image, and for some images that are still unclear, they need to be replaced with clearer ones. If you encounter any problems, feel free to drop me a line ～ Thanks 😄

Thinks,i will

**Comment by hanzhenfang** [comment]
@guoqqqi @juzhiyuan 
Hello, There are some questions when I try to solve the issue.🤔
1. Whether the order of ICONS is important? 
2. I found that when I looked for clearer images, some of them were not the same， such as
![image](https://user-images.githubusercontent.com/99874763/158041415-5842fb4d-1223-4834-85f4-81a85880e67f.png)
it's so fuzzy that I couldn't find the same images. But I find some similar images of them,
![image](https://user-images.githubusercontent.com/99874763/158041501-1b5d178f-8f0e-4be5-a511-c1698ae637b3.png)
Whether this solution can be used？

**Comment by hanzhenfang** [comment]
@guoqqqi 
hey, I have replaced nine pictures like these. 
The old:
![image](https://user-images.githubusercontent.com/99874763/158051186-d9939a14-0b7a-43d3-b746-2925c8a45610.png). ![image](https://user-images.githubusercontent.com/99874763/158051277-002beb24-639b-4f76-9e49-0b1da92d7aae.png)![image](https://user-images.githubusercontent.com/99874763/158051299-c94d5033-1a9e-4dbd-9150-ad840bd0dbdb.png)![image](https://user-images.githubusercontent.com/99874763/158051365-5c95452f-d45c-4844-a316-cccc14231e92.png)![image](https://user-images.githubusercontent.com/99874763/158051374-a0ac41fa-6081-4b92-84a4-e717d252b615.png)


The new:
<img width="142" alt="image" src="https://user-images.githubusercontent.com/99874763/158051211-2ba3a20b-8e10-4638-9d4f-a4759dc05103.png"><img width="126" alt="image" src="https://user-images.githubusercontent.com/99874763/158051285-6d36d42a-2fdf-4a4d-87d7-ff6f9e3e2cf8.png"><img width="105" alt="image" src="https://user-images.githubusercontent.com/99874763/158051314-552c96b1-f5ce-441c-8644-9b5df4abda4f.png"><img width="119" alt="image" src="https://user-images.githubusercontent.com/99874763/158051339-02913067-a143-4bf1-afaf-6c57eeaf6fdd.png"><img width="109" alt="image" src="https://user-images.githubusercontent.com/99874763/158051382-36bbaa54-6435-4f55-952a-21addb24e467.png">
And so on.
I also add some Media queries to make the page look better in a small screen like this.
![image](https://user-images.githubusercontent.com/99874763/158051611-b2f9f358-5d87-4a90-9283-798b55d3bffa.png)
<img width="813" alt="image" src="https://user-images.githubusercontent.com/99874763/158051638-cf5d4e53-e441-4a43-a122-b359629478ac.png">

**Comment by hanzhenfang** [comment]
@guoqqqi And I think I can make the page more beautiful if you give me some suggestions.😊

**Comment by guoqqqi** [comment]
Hi, @hanzhenfang I have not to see your PR, please create your PR, then we can talk about it
