### ISSUE TITLE
[Site]: URL case-sensitive of Docusaurus Rendered pages

### ISSUE THREAD

**Issue by juzhiyuan** [iresty/iresty.github.io#957]
### Current State

**Description of the current state/issue**: 404 Not Found

**Link to the page**: https://apisix.apache.org/blog/2021/08/05/Kong-to-APISIX/

### Desired State

**Description of the change you are proposing**:

It works if we visit `https://apisix.apache.org/blog/2021/08/05/kong-to-apisix/`.

### Would you like to fix this issue?

No. Please assign another contributor. Reporter: @lilien1010

### NOTES

1. After Docusaurus build the markdown files, all files are under the `asf-site` branch, check https://github.com/apache/apisix-website/tree/asf-site/blog/2021/08/05/kong-to-apisix

**Comment by juzhiyuan** [comment]
If we could configure Web Server to support URL case-insensitive? so it supports both `Kong-to-APISIX` and `kong-to-apisix`. This depends on the ASF Infra.

**Comment by SkyeYoung** [comment]
>> But I think plugin-client-redirect should work, I will try to fix the problem of it. Maybe one day.😜
>
> @juzhiyuan I think I have made Client Redirect working properly in https://github.com/apache/apisix-website/pull/986. So what should we do now?
>
> _Originally posted by @SkyeYoung in https://github.com/apache/apisix-website/issues/945#issuecomment-1092349685_

@juzhiyuan Maybe we can close this.

**Comment by juzhiyuan** [comment]
Maybe we could configure .htaccess according to https://github.com/apache/apisix-website/pull/1067?

**Comment by juzhiyuan** [comment]
Done
