### ISSUE TITLE
[Site]: Add lint tools to standardize code style

### ISSUE THREAD

**Issue by SkyeYoung** [iresty/iresty.github.io#967]
### Current State

**Description of the current state/issue**:
If we have prettier, eslint, and lint-staged, husky, We will have a better development experience.

**Link to the page**:

**Screenshots (if relevant)**:

### Desired State

**Description of the change you are proposing**:

### Would you like to fix this issue?

Yes! Count me in

**Comment by leslie-tsang** [comment]
SGTM, thanks for your contribution.
