### ISSUE TITLE
[Site]: fix skewed images

### ISSUE THREAD

**Issue by pottekkat** [iresty/iresty.github.io#983]
### Current State

**Description of the current state/issue**:

The screenshots in the homepage are skewed.

**Link to the page**: https://apisix.apache.org/

**Screenshots (if relevant)**:

![Screenshot 2022-03-29 at 5 40 24 PM](https://user-images.githubusercontent.com/49474499/160608634-c2c0b639-4504-4040-baa6-19bd6ad30895.png)

![Screenshot 2022-03-29 at 5 40 34 PM](https://user-images.githubusercontent.com/49474499/160608657-84452915-fb4d-4199-9643-31cab8c9e7b5.png)

### Desired State

**Description of the change you are proposing**:

The image should not be skewed but instead cropped properly or resized proportionally.

### Would you like to fix this issue?

No. Please assign another contributor

**Comment by pottekkat** [comment]
Please tag this as a "good first issue".

**Comment by 0xRai** [comment]
Is this still open for an assignee? I would be willing to help.

**Comment by pottekkat** [comment]
@RaiIsNotYourGuy Go ahead. @leslie-tsang Will assign this to you.

**Comment by leslie-tsang** [comment]
> Is this still open for an assignee? I would be willing to help.

Assigned. Thanks. :)
