### ISSUE TITLE
Support Client Redirect to avoid broken links

### ISSUE THREAD

**Issue by juzhiyuan** [iresty/iresty.github.io#985]
Don't worry. Could you help list all broken links after this PR gets merged? And we could seek help from @SkyeYoung to implement this.

_Originally posted by @juzhiyuan in https://github.com/apache/apisix-website/pull/974#discussion_r836976994_

**Comment by juzhiyuan** [comment]
After discussion, I will assign to @SkyeYoung

**Comment by pottekkat** [comment]
This will give an idea about the broken links and where to redirect them to: https://github.com/apache/apisix-website/pull/974/files#diff-967d1dba796f3953f3289cb17f80bac57e3c812daaffd07fc8fca096ab80d310
