### ISSUE TITLE
[Docs]: update README.md

### ISSUE THREAD

**Issue by SkyeYoung** [iresty/iresty.github.io#989]
### Current State

**Description of the current state/issue**:

Related: https://github.com/apache/apisix-website/pull/984, https://github.com/apache/apisix-website/pull/972

After above PRs are merged, We need to update README.md to help contributors develop and build.

**Link to the page**:
none

**Screenshots (if relevant)**:
none

### Desired State

**Description of the change you are proposing**:

### Would you like to fix this issue?

Yes! Count me in

**Comment by Ps066** [comment]
Yes !! i am interested to work in it , do let me know what changes need to be done

**Comment by SkyeYoung** [comment]
> Yes !! i am interested to work in it , do let me know what changes need to be done

@Ps066 Great!

The main content we need to amend is the Usage. So what you can do is:

1. rewrite current part, now we just need to run `yarn start` under the project root directory
2. now it's all about dev mode guide, we need to add build related guidance. (For example, `yarn build && yarn docusaurus serve --host 0.0.0.0` )
3. write down some commands, instructions, and document links you think everyone may need in the deployment process.
4. keep it as simple and necessary as possible

Refs:

1. https://github.com/apache/apisix-website/blob/master/.github/workflows/deploy.yml
2. https://github.com/apache/apisix-website/blob/master/package.json
3. https://docusaurus.io/docs/cli
4. https://yarnpkg.com/cli/workspace

**Comment by Ps066** [comment]
thankyou @SkyeYoung  for assigning me , and helping me !! i started working on it will complete as soon as possible

**Comment by Ps066** [comment]
Fixes #989 

Changes done :-

- [X] Added a basic guide for Environment setup
- [X]  Added a guide to start & run the server 
- [X]  Tried to simplify the Docusaurus Documentation

Screenshots :-
![image](https://user-images.githubusercontent.com/81038824/161287092-2827cf08-d51a-4844-8f0b-0d0778200f00.png)
![image](https://user-images.githubusercontent.com/81038824/161287238-18e7b6ea-c5dd-4aa7-91d5-8f39fe6eab15.png)

Have a look to documentation , at [https://github.com/Ps066/apisix-website/blob/master/README.md](url)
Please look through the new Readme documentations , and do let me know if any changes are required.
