### ISSUE TITLE
[Docs]: Track canonical_url's actual behavior

### ISSUE THREAD

**Issue by yzeng25** [iresty/iresty.github.io#999]
### Current State

**Description of the current state/issue**:

Some of the APISIX blogs are cross-posted on other platforms such as Medium or other communities' blog websites. While Medium provides canonical url to point to the original post, other communities' blog websites lack of this feature. This could create negative effects on SEO.

Currently, we are unsure about the actual effect of canonical_url, and we are going to add canonical_url to a recently published blog to see if it brings difference, see https://github.com/apache/apisix-website/pull/995. 

**Link to the page**:
https://apisix.apache.org/blog/2022/02/28/apisix-integration-opentelemetry-plugin/

**Screenshots (if relevant)**:
none.

### Desired State

**Description of the change you are proposing**:

We should review GA stats after a month or so, preferably early May, to see if canonical_url actually works. If it works, then we should do it for each cross-posted blog that is posted on platforms other than Medium. If it does not work, we should rollback the change in this pull request.

**How to determine if it has effect**

**Expected Changes**

According to the definition of usages of canonical_url, it will reduce duplicate and return only one result. In this case, Medium applies canonical_url and points to APISIX's blog, then we apply canonical_url on APISIX's blog and points to OpenTelemetry's blog.

In the end, Medium's link won't show up, ideally APISIX's blog won't show up either, and only OpenTelemetry's blog will show up(not sure if nested canonical_url works like this).

**View Count**: if its view count of APISIX's blog conentent does not differ much from other blogs posted in the same period of time, then we can say canonical_url  has less effect, we should reconsider adding it to all cross-posted articles.

**Search Engine Results**: 
Before adding canonical_url, when typing  "apisix opentelemetry" or "opentelemetry apisix" in Google, the results are:
![image](https://user-images.githubusercontent.com/36651058/161235801-36f91dd7-4ed5-4fe1-8cce-726d75b2ee1b.png)
![image](https://user-images.githubusercontent.com/36651058/161235915-8f29f4d7-2ed7-41fe-ae0f-c2ef03a22e6f.png)

We'd expect only OpenTelemetry's blog will show up, or at least both APISIX's blog and OpenTelemetry's blog will show up, with OpenTelemetry's blog in front of APISIX's blog. Otherwise, this pull request is proven to be wrong.

### Would you like to fix this issue?

Yes! Count me in

**Comment by yzeng25** [comment]
Hi, should we postpone it to early June due to website refactor in https://github.com/apache/apisix-website/issues/1048?

**Comment by SkyeYoung** [comment]
> Hi, should we postpone it to early June due to website refactor in #1048?

🤔 I'm not familiar with this. Maybe not, because all links will remain as they are.

**Comment by yzeng25** [comment]
> > Hi, should we postpone it to early June due to website refactor in #1048?
> 
> 🤔 I'm not familiar with this. Maybe not, because all links will remain as they are.

Ok, I thought there might be repeated work, guess I am wrong.

**Comment by yzeng25** [comment]
It is about time to get the data and see what actions are needed now @SkyeYoung @nfrankel @juzhiyuan .

**Comment by SkyeYoung** [comment]
> It is about time to get the data and see what actions are needed now @SkyeYoung @nfrankel @juzhiyuan .

@juzhiyuan could you help us check this?

**Comment by juzhiyuan** [comment]
> It is about time to get the data and see what actions are needed now @SkyeYoung @nfrankel @juzhiyuan .

Hi, @yzeng25. After talking with @SkyeYoung, we both are not familiar with this and don't know what actionable items should we do. Could you please list steps or you could directly check?

**Comment by yzeng25** [comment]
@juzhiyuan @SkyeYoung So basically this is it. 

> We'd expect only OpenTelemetry's blog will show up, or at least both APISIX's blog and OpenTelemetry's blog will show up, with OpenTelemetry's blog in front of APISIX's blog. Otherwise, this pull request is proven to be wrong.

I typed in 'apisix opentelemetry' and 'opentelemetry apisix' in Google, and OpenTelemetry's blog shows up in front of APISIX's blog. This indicates the canonical_url added in https://github.com/apache/apisix-website/pull/995 is working as expected.

Next steps:

1. Find a list of collaborations/ecosystem blogs on APISIX's site.
2. Add canonical_url to them, just like https://github.com/apache/apisix-website/pull/995.
